'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, CheckCircle2, Clock, GraduationCap, Sparkles } from 'lucide-react';
import { SiteHeader } from '@/components/marketing/site-header';
import { SiteFooter } from '@/components/marketing/site-footer';
import { Button } from '@/components/ui/button';
import { getPrograms } from '@/lib/api';
import type { Program } from '@/lib/api/types';

export default function ProgramsLandingPage() {
  const [programs, setPrograms] = useState<Program[]>([]);
  useEffect(() => { getPrograms().then(setPrograms).catch(() => setPrograms([])); }, []);
  return <div className="min-h-screen bg-slate-50"><SiteHeader /><main>
    <section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="font-semibold text-blue-400">PROGRAMS</p><h1 className="mt-3 max-w-4xl text-5xl font-extrabold tracking-tight sm:text-6xl">Build skills that move your career forward.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Structured academic pathways with AI-powered support, practical projects and clear progression from learning to opportunity.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-full bg-blue-600"><Link href="/register">Start Learning <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline" className="rounded-full border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white"><Link href="/opportunities">Explore Opportunities</Link></Button></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-5 sm:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-sm"><GraduationCap className="h-7 w-7 text-blue-700"/><h3 className="mt-4 font-bold">Academic pathways</h3><p className="mt-2 text-sm text-slate-600">Programs designed around progression and recognized outcomes.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><Sparkles className="h-7 w-7 text-violet-700"/><h3 className="mt-4 font-bold">AI-assisted study</h3><p className="mt-2 text-sm text-slate-600">Personalized tutoring, revision and feedback when you need it.</p></div><div className="rounded-3xl bg-white p-6 shadow-sm"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><h3 className="mt-4 font-bold">Career relevance</h3><p className="mt-2 text-sm text-slate-600">Learning connected to portfolios, projects and opportunity.</p></div></div></section>
    <section className="bg-slate-100 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-extrabold">Explore programs</h2><p className="mt-2 text-slate-600">Choose a pathway and start building your future.</p><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{programs.length ? programs.map((p) => <Link href={`/programs/${p.id}`} key={p.id} className="group rounded-3xl bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex justify-between"><BookOpen className="h-7 w-7 text-blue-700"/><ArrowRight className="h-5 w-5 text-slate-300 group-hover:text-blue-700"/></div><h3 className="mt-7 text-xl font-bold">{p.name}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{p.description || 'Explore this academic pathway and its learning outcomes.'}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">View program <ArrowRight className="h-4 w-4"/></span></Link>) : <div className="rounded-3xl bg-white p-8 text-slate-600 md:col-span-2 lg:col-span-3">Programs are being prepared. <Link href="/register" className="font-semibold text-blue-700">Join UnivAI</Link> to be notified.</div>}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="rounded-[2rem] bg-gradient-to-r from-blue-700 to-violet-700 p-10 text-white sm:p-14"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="font-semibold text-blue-200">YOUR NEXT CHAPTER</p><h2 className="mt-2 text-3xl font-extrabold">Learn with purpose. Graduate with momentum.</h2></div><Button asChild size="lg" className="rounded-full bg-white text-blue-700 hover:bg-blue-50"><Link href="/register">Apply now</Link></Button></div></div></section>
  </main><SiteFooter /></div>;
}
