<?php

namespace App\Support\Branding;

use App\Models\Application;
use App\Models\Program;

class UnivAiBranding
{
    public static function brand(): array
    {
        return config('univai.brand', []);
    }

    public static function name(): string
    {
        return (string) (self::brand()['name'] ?? 'UnivAI');
    }

    public static function legalName(): string
    {
        return (string) (self::brand()['legal_name'] ?? self::name());
    }

    public static function tagline(): string
    {
        return 'Unlocking Intelligence';
    }

    public static function officialOffice(): string
    {
        return 'Office of Admissions and Academic Registry';
    }

    public static function documentSubtitle(): string
    {
        return self::officialOffice();
    }

    public static function supportEmail(): string
    {
        return (string) (self::brand()['support_email'] ?? 'support@univai.edu');
    }

    public static function admissionsEmail(): string
    {
        return (string) (self::brand()['admissions_email'] ?? self::supportEmail());
    }

    public static function publicUrl(): string
    {
        return rtrim((string) (self::brand()['public_url'] ?? config('app.url')), '/');
    }

    public static function publicFooter(): string
    {
        return implode("\n", [
            self::name() . ' - ' . self::tagline(),
            self::officialOffice(),
            'Admissions: ' . self::admissionsEmail(),
            'Portal: ' . self::publicUrl(),
        ]);
    }

    public static function admissionsSignature(): string
    {
        return implode("\n", [
            'Sincerely,',
            self::name() . ' Admissions Office',
            self::officialOffice(),
            self::admissionsEmail(),
        ]);
    }

    public static function documentVerificationNotice(): string
    {
        return 'Document Verification: This document was generated by ' . self::name() . ' and should be verified through the official ' . self::name() . ' Admissions Portal.';
    }

    public static function offerLetterText(Application $application): string
    {
        $details = self::applicationProgrammeDetails($application);
        $body = $application->offer_letter_message
            ?: 'Congratulations. After reviewing your application, ' . self::name() . ' is pleased to offer you provisional admission into the programme listed below.';

        return implode("\n", array_filter([
            strtoupper(self::name()),
            self::officialOffice(),
            self::legalName(),
            '',
            'PROVISIONAL OFFER LETTER',
            '',
            'Reference: ' . $application->reference,
            'Date Issued: ' . now()->toFormattedDateString(),
            '',
            "Dear {$application->full_name},",
            '',
            $body,
            '',
            'Programme Details',
            'Programme: ' . $details['programTitle'],
            $details['qualification'] ? 'Qualification: ' . $details['qualification'] : null,
            $details['schoolName'] ? 'School / Faculty: ' . $details['schoolName'] : null,
            $details['departmentName'] ? 'Department: ' . $details['departmentName'] : null,
            'Delivery Mode: ' . ($application->delivery_mode ?: 'To be confirmed'),
            'Intake: ' . ($application->intake_id ?: 'To be confirmed'),
            '',
            'Conditions of Offer',
            '1. Verification of all submitted academic and identity documents.',
            '2. Acceptance of this offer through the ' . self::name() . ' Admissions Portal.',
            '3. Payment of applicable admissions and enrollment fees.',
            '4. Completion of the official enrollment process.',
            '5. Compliance with ' . self::name() . ' academic and student policies.',
            '',
            $details['requirements'] ? 'Published Admission Requirements: ' . $details['requirements'] : null,
            '',
            'Please log in to the ' . self::name() . ' Admissions Portal to accept this offer and continue to enrollment:',
            self::publicUrl() . '/admissions/status',
            '',
            self::admissionsSignature(),
            '',
            self::documentVerificationNotice(),
            '',
            self::publicFooter(),
        ], fn ($line) => $line !== null));
    }

    public static function admissionLetterText(Application $application): string
    {
        $details = self::applicationProgrammeDetails($application);

        return implode("\n", array_filter([
            strtoupper(self::name()),
            self::officialOffice(),
            self::legalName(),
            '',
            'OFFICIAL ADMISSION LETTER',
            '',
            'Reference: ' . $application->reference,
            'Date Issued: ' . now()->toFormattedDateString(),
            '',
            "Dear {$application->full_name},",
            '',
            'Following your acceptance of the offer issued by ' . self::name() . ', we are pleased to confirm that you have been officially admitted into the programme listed below.',
            '',
            'Programme Details',
            'Programme: ' . $details['programTitle'],
            $details['qualification'] ? 'Qualification: ' . $details['qualification'] : null,
            $details['schoolName'] ? 'School / Faculty: ' . $details['schoolName'] : null,
            $details['departmentName'] ? 'Department: ' . $details['departmentName'] : null,
            'Delivery Mode: ' . ($application->delivery_mode ?: 'To be confirmed'),
            'Intake: ' . ($application->intake_id ?: 'To be confirmed'),
            '',
            'Enrollment Instructions',
            'Your admission is recorded subject to completion of the final enrollment requirements, including module selection, confirmation of delivery mode, payment of applicable fees, and compliance with ' . self::name() . ' academic policies.',
            '',
            'Please proceed to the ' . self::name() . ' Enrollment Portal to complete your enrollment. Once enrollment is completed, your full Student Dashboard will be activated.',
            self::publicUrl() . '/student/enroll',
            '',
            self::admissionsSignature(),
            '',
            self::documentVerificationNotice(),
            '',
            self::publicFooter(),
        ], fn ($line) => $line !== null));
    }

    private static function applicationProgrammeDetails(Application $application): array
    {
        $program = Program::with(['school', 'department', 'qualificationLevel'])->find($application->program_id);

        return [
            'programTitle' => $program?->title ?? $application->program_id,
            'schoolName' => $program?->school?->name,
            'departmentName' => $program?->department?->name,
            'qualification' => $program?->qualificationLevel?->name,
            'requirements' => $program?->admission_requirements,
        ];
    }

    public static function emailSubject(string $subject): string
    {
        return '[' . self::name() . '] ' . $subject;
    }
}
