<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UnivAiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->upsert([
            [
                'name' => 'Admin',
                'email' => 'admin@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lecturer',
                'email' => 'lecturer@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'lecturer',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lecturer A',
                'email' => 'lecturer.a@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'lecturer',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lecturer B',
                'email' => 'lecturer.b@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'lecturer',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Employer',
                'email' => 'employer@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'employer',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Premium Student',
                'email' => 'student.premium@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'premium-student',
                'school_id' => 'ict',
                'program_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Freemium Student',
                'email' => 'student.freemium@univai.edu',
                'password' => Hash::make('password123'),
                'role' => 'freemium-student',
                'school_id' => null,
                'program_id' => null,
                'intake_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['email'], ['name', 'password', 'role', 'school_id', 'program_id', 'updated_at']);

        DB::table('schools')->upsert([
            ['id' => 'edu', 'name' => 'School of Education', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'ict', 'name' => 'School of ICT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'nursing', 'name' => 'School of Nursing', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'business', 'name' => 'School of Business', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'eng', 'name' => 'School of Engineering', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['name', 'updated_at']);

        DB::table('admissions_settings')->updateOrInsert(
            ['id' => 1],
            [
                'is_open' => true,
                'message' => null,
                'updated_at' => now(),
                'created_at' => now(),
            ]
        );

        DB::table('academic_policies')->upsert([
            [
                'id' => 1,
                'name' => 'Standard ZM (Pass 50 / Best Attempt)',
                'pass_mark' => 50,
                'exam_minimum' => null,
                'gpa_scale_type' => '4.0',
                'grade_bands' => json_encode([
                    ['min' => 70, 'max' => 100, 'letter' => 'A', 'points' => 4.0],
                    ['min' => 60, 'max' => 69, 'letter' => 'B', 'points' => 3.0],
                    ['min' => 50, 'max' => 59, 'letter' => 'C', 'points' => 2.0],
                    ['min' => 40, 'max' => 49, 'letter' => 'D', 'points' => 1.0],
                    ['min' => 0, 'max' => 39, 'letter' => 'F', 'points' => 0.0],
                ]),
                'repeat_rule' => 'best',
                'max_attempts' => 3,
                'include_failed_in_gpa' => true,
                'include_withdrawn_in_gpa' => false,
                'credit_award_policy' => 'pass_only',
                'condoned_mark' => null,
                'progression_policy' => json_encode([
                    'min_pass_percent' => 0.6,
                    'probation_limit' => 2,
                    'carry_limit' => 2,
                ]),
                'holds_policy' => json_encode([
                    'registration' => true,
                    'course_access' => true,
                    'exam_entry' => true,
                    'results_release' => true,
                ]),
                'rounding_decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Strict (Pass 60 / Latest Attempt)',
                'pass_mark' => 60,
                'exam_minimum' => null,
                'gpa_scale_type' => '4.0',
                'grade_bands' => json_encode([
                    ['min' => 80, 'max' => 100, 'letter' => 'A', 'points' => 4.0],
                    ['min' => 70, 'max' => 79, 'letter' => 'B', 'points' => 3.0],
                    ['min' => 60, 'max' => 69, 'letter' => 'C', 'points' => 2.0],
                    ['min' => 50, 'max' => 59, 'letter' => 'D', 'points' => 1.0],
                    ['min' => 0, 'max' => 49, 'letter' => 'F', 'points' => 0.0],
                ]),
                'repeat_rule' => 'latest',
                'max_attempts' => 2,
                'include_failed_in_gpa' => true,
                'include_withdrawn_in_gpa' => false,
                'credit_award_policy' => 'pass_only',
                'condoned_mark' => null,
                'progression_policy' => json_encode([
                    'min_pass_percent' => 0.7,
                    'probation_limit' => 1,
                    'carry_limit' => 1,
                ]),
                'holds_policy' => json_encode([
                    'registration' => true,
                    'course_access' => true,
                    'exam_entry' => true,
                    'results_release' => true,
                ]),
                'rounding_decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Average Attempts (Pass 50 / Average)',
                'pass_mark' => 50,
                'exam_minimum' => null,
                'gpa_scale_type' => '4.0',
                'grade_bands' => json_encode([
                    ['min' => 70, 'max' => 100, 'letter' => 'A', 'points' => 4.0],
                    ['min' => 60, 'max' => 69, 'letter' => 'B', 'points' => 3.0],
                    ['min' => 50, 'max' => 59, 'letter' => 'C', 'points' => 2.0],
                    ['min' => 40, 'max' => 49, 'letter' => 'D', 'points' => 1.0],
                    ['min' => 0, 'max' => 39, 'letter' => 'F', 'points' => 0.0],
                ]),
                'repeat_rule' => 'average',
                'max_attempts' => 3,
                'include_failed_in_gpa' => true,
                'include_withdrawn_in_gpa' => false,
                'credit_award_policy' => 'pass_only',
                'condoned_mark' => null,
                'progression_policy' => json_encode([
                    'min_pass_percent' => 0.6,
                    'probation_limit' => 2,
                    'carry_limit' => 2,
                ]),
                'holds_policy' => json_encode([
                    'registration' => true,
                    'course_access' => true,
                    'exam_entry' => true,
                    'results_release' => true,
                ]),
                'rounding_decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'All Attempts Count (Pass 50 / All)',
                'pass_mark' => 50,
                'exam_minimum' => null,
                'gpa_scale_type' => '4.0',
                'grade_bands' => json_encode([
                    ['min' => 70, 'max' => 100, 'letter' => 'A', 'points' => 4.0],
                    ['min' => 60, 'max' => 69, 'letter' => 'B', 'points' => 3.0],
                    ['min' => 50, 'max' => 59, 'letter' => 'C', 'points' => 2.0],
                    ['min' => 40, 'max' => 49, 'letter' => 'D', 'points' => 1.0],
                    ['min' => 0, 'max' => 39, 'letter' => 'F', 'points' => 0.0],
                ]),
                'repeat_rule' => 'all',
                'max_attempts' => 3,
                'include_failed_in_gpa' => true,
                'include_withdrawn_in_gpa' => false,
                'credit_award_policy' => 'pass_only',
                'condoned_mark' => null,
                'progression_policy' => json_encode([
                    'min_pass_percent' => 0.6,
                    'probation_limit' => 2,
                    'carry_limit' => 2,
                ]),
                'holds_policy' => json_encode([
                    'registration' => true,
                    'course_access' => true,
                    'exam_entry' => true,
                    'results_release' => true,
                ]),
                'rounding_decimals' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['name', 'pass_mark', 'gpa_scale_type', 'grade_bands', 'repeat_rule', 'max_attempts', 'include_failed_in_gpa', 'include_withdrawn_in_gpa', 'credit_award_policy', 'condoned_mark', 'progression_policy', 'holds_policy', 'rounding_decimals', 'updated_at']);

        DB::table('courses')->upsert([
            [
                'id' => 'cs101',
                'school_id' => 'ict',
                'title' => 'Bachelor of Science in Software Development and Emerging Technologies',
                'description' => 'Foundational concepts of computing, including algorithms, data structures, and software engineering.',
                'progress' => 100,
                'image_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'nur201',
                'school_id' => 'nursing',
                'title' => 'Diploma in Nursing',
                'description' => 'Essential skills for patient care, clinical practice, and medical ethics.',
                'progress' => 45,
                'image_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301',
                'school_id' => 'business',
                'title' => 'MBA',
                'description' => 'Advanced business administration, leadership, and strategic management.',
                'progress' => 90,
                'image_id' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'eng401',
                'school_id' => 'eng',
                'title' => 'Mechanical Engineering',
                'description' => 'Principles of mechanics, thermodynamics, and material science.',
                'progress' => 20,
                'image_id' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'edu110',
                'school_id' => 'edu',
                'title' => 'Early Childhood Education',
                'description' => 'Theories and practices for teaching young children from birth to age 8.',
                'progress' => 60,
                'image_id' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'description', 'school_id', 'progress', 'image_id', 'updated_at']);

        DB::table('programs')->upsert([
            [
                'id' => 'cs101',
                'school_id' => 'ict',
                'title' => 'Bachelor of Science in Software Development and Emerging Technologies',
                'description' => 'Duration: 4 years (8 semesters). Delivery: 100% online with AI tutors and virtual labs.',
                'progress' => 100,
                'image_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301',
                'school_id' => 'business',
                'title' => 'MBA',
                'description' => 'Duration: 2 years (4 semesters). Delivery: hybrid with weekend intensives and online classes.',
                'progress' => 0,
                'image_id' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'nur201',
                'school_id' => 'nursing',
                'title' => 'Diploma in Nursing',
                'description' => 'Duration: 3 years (6 semesters). Delivery: physical labs with online theory.',
                'progress' => 0,
                'image_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'eng401',
                'school_id' => 'eng',
                'title' => 'Mechanical Engineering',
                'description' => 'Duration: 4 years (8 semesters). Delivery: physical labs and hybrid lectures.',
                'progress' => 0,
                'image_id' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'edu110',
                'school_id' => 'edu',
                'title' => 'Early Childhood Education',
                'description' => 'Duration: 3 years (6 semesters). Delivery: blended learning with school placements.',
                'progress' => 0,
                'image_id' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'description', 'progress', 'image_id', 'updated_at']);

        DB::table('curriculum_versions')->upsert([
            [
                'id' => 'cs101-v2026',
                'program_id' => 'cs101',
                'name' => 'Curriculum 2026',
                'status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301-v2026',
                'program_id' => 'bus301',
                'name' => 'Curriculum 2026',
                'status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'nur201-v2026',
                'program_id' => 'nur201',
                'name' => 'Curriculum 2026',
                'status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'eng401-v2026',
                'program_id' => 'eng401',
                'name' => 'Curriculum 2026',
                'status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'edu110-v2026',
                'program_id' => 'edu110',
                'name' => 'Curriculum 2026',
                'status' => 'published',
                'published_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['name', 'status', 'published_at', 'updated_at']);

        DB::table('program_policies')->updateOrInsert(
            ['program_id' => 'cs101'],
            ['policy_id' => 1, 'created_at' => now(), 'updated_at' => now()]
        );

        DB::table('curriculum_version_policies')->updateOrInsert(
            ['curriculum_version_id' => 'cs101-v2026'],
            ['policy_id' => 1, 'created_at' => now(), 'updated_at' => now()]
        );

        DB::table('intakes')->upsert([
            [
                'id' => 'cs101-2026-jan',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'name' => 'Jan 2026 Intake',
                'delivery_mode' => 'hybrid',
                'campus' => 'Lusaka Campus',
                'capacity' => 200,
                'start_date' => now()->toDateString(),
                'end_date' => now()->addMonths(4)->toDateString(),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'cs101-2026-jun',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'name' => 'Jun 2026 Intake',
                'delivery_mode' => 'online',
                'campus' => null,
                'capacity' => 300,
                'start_date' => now()->addMonths(4)->toDateString(),
                'end_date' => now()->addMonths(8)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301-2026-jan',
                'program_id' => 'bus301',
                'curriculum_version_id' => 'bus301-v2026',
                'name' => 'Jan 2026 Intake',
                'delivery_mode' => 'hybrid',
                'campus' => 'Lusaka Campus',
                'capacity' => 120,
                'start_date' => now()->toDateString(),
                'end_date' => now()->addMonths(6)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301-2026-jun',
                'program_id' => 'bus301',
                'curriculum_version_id' => 'bus301-v2026',
                'name' => 'Jun 2026 Intake',
                'delivery_mode' => 'online',
                'campus' => null,
                'capacity' => 150,
                'start_date' => now()->addMonths(5)->toDateString(),
                'end_date' => now()->addMonths(10)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'nur201-2026-jan',
                'program_id' => 'nur201',
                'curriculum_version_id' => 'nur201-v2026',
                'name' => 'Jan 2026 Intake',
                'delivery_mode' => 'physical',
                'campus' => 'Lusaka Campus',
                'capacity' => 80,
                'start_date' => now()->toDateString(),
                'end_date' => now()->addMonths(6)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'eng401-2026-jan',
                'program_id' => 'eng401',
                'curriculum_version_id' => 'eng401-v2026',
                'name' => 'Jan 2026 Intake',
                'delivery_mode' => 'hybrid',
                'campus' => 'Copperbelt Campus',
                'capacity' => 100,
                'start_date' => now()->toDateString(),
                'end_date' => now()->addMonths(6)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'edu110-2026-jan',
                'program_id' => 'edu110',
                'curriculum_version_id' => 'edu110-v2026',
                'name' => 'Jan 2026 Intake',
                'delivery_mode' => 'hybrid',
                'campus' => 'Lusaka Campus',
                'capacity' => 140,
                'start_date' => now()->toDateString(),
                'end_date' => now()->addMonths(6)->toDateString(),
                'status' => 'open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['name', 'delivery_mode', 'campus', 'capacity', 'start_date', 'end_date', 'status', 'curriculum_version_id', 'updated_at']);

        DB::table('program_modules')->upsert([
            [
                'id' => 'cs101-sem1-1',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'title' => 'Introduction to ICT and Digital Literacy',
                'description' => 'Overview of computers, networks, and digital systems.',
                'credits' => 6,
                'progress' => 100,
                'semester' => 1,
                'is_exam_available' => true,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'cs101-sem1-2',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'title' => 'Fundamentals of Programming',
                'description' => 'Introduction to programming using Python.',
                'credits' => 6,
                'progress' => 100,
                'semester' => 1,
                'is_exam_available' => false,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'cs101-sem1-3',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'title' => 'Mathematics for Computer Science I',
                'description' => 'Logic, sets, functions, and basic discrete math.',
                'credits' => 6,
                'progress' => 100,
                'semester' => 1,
                'is_exam_available' => false,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'cs101-sem1-4',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'title' => 'Introduction to Artificial Intelligence',
                'description' => 'History and applications of AI.',
                'credits' => 6,
                'progress' => 100,
                'semester' => 1,
                'is_exam_available' => false,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'cs101-sem1-5',
                'program_id' => 'cs101',
                'curriculum_version_id' => 'cs101-v2026',
                'title' => 'Professional Development & Ethics',
                'description' => 'Digital ethics, professionalism, and communication skills.',
                'credits' => 3,
                'progress' => 100,
                'semester' => 1,
                'is_exam_available' => false,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301-sem1-1',
                'program_id' => 'bus301',
                'curriculum_version_id' => 'bus301-v2026',
                'title' => 'Strategic Management Fundamentals',
                'description' => 'Foundations of competitive strategy and corporate positioning.',
                'credits' => 6,
                'progress' => 0,
                'semester' => 1,
                'is_exam_available' => true,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'bus301-sem1-2',
                'program_id' => 'bus301',
                'curriculum_version_id' => 'bus301-v2026',
                'title' => 'Financial Decision-Making',
                'description' => 'Budgeting, forecasting, and investment analysis for managers.',
                'credits' => 6,
                'progress' => 0,
                'semester' => 1,
                'is_exam_available' => false,
                'is_core' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'description', 'progress', 'semester', 'is_exam_available', 'is_core', 'curriculum_version_id', 'updated_at']);

        DB::table('lessons')->upsert([
            [
                'id' => 'l1-cs101',
                'course_id' => 'cs101',
                'title' => 'Digital Systems Overview',
                'content' => 'An overview of modern computer hardware, software, and networking components.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l2-cs101',
                'course_id' => 'cs101',
                'title' => 'Cloud Collaboration',
                'content' => 'Hands-on skills using cloud storage and collaborative tools like Google Workspace.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l3-cs101',
                'course_id' => 'cs101',
                'title' => 'Intro to Python',
                'content' => 'Learn the fundamentals of the Python programming language, including variables and control flow.',
                'video_url' => 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'quiz' => json_encode([
                    'title' => 'Python Basics Check',
                    'questions' => [
                        [
                            'question' => 'Which keyword creates a conditional block in Python?',
                            'options' => ['if', 'loop', 'define', 'switch'],
                            'answer' => 'if',
                        ],
                        [
                            'question' => 'What data type is "42" in Python?',
                            'options' => ['int', 'string', 'float', 'bool'],
                            'answer' => 'string',
                        ],
                    ],
                ]),
                'exercise' => 'Write a short program that asks for a name and prints a personalized greeting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l4-cs101',
                'course_id' => 'cs101',
                'title' => 'Data Representation',
                'content' => 'How data is represented in binary, hexadecimal, and structured formats.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l5-cs101',
                'course_id' => 'cs101',
                'title' => 'Algorithms in Everyday Systems',
                'content' => 'Understanding how algorithms power search, recommendations, and automation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l6-cs101',
                'course_id' => 'cs101',
                'title' => 'Ethics in Emerging Tech',
                'content' => 'Ethical considerations for AI, privacy, and responsible innovation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l7-cs101',
                'course_id' => 'cs101',
                'title' => 'Collaboration & Version Control',
                'content' => 'Working with teams, version control basics, and academic integrity in group projects.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l8-cs101',
                'course_id' => 'cs101',
                'title' => 'Programming Fundamentals Lab',
                'content' => 'Hands-on lab to practice input/output, conditions, and loops.',
                'exercise' => 'Create a simple calculator that adds and subtracts two numbers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l9-cs101',
                'course_id' => 'cs101',
                'title' => 'AI in Society',
                'content' => 'Case studies on how AI impacts education, health, and business.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l1-bus301',
                'course_id' => 'bus301',
                'title' => 'Strategic Leadership Foundations',
                'content' => 'Leadership models, decision-making frameworks, and strategy alignment.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'l2-bus301',
                'course_id' => 'bus301',
                'title' => 'Business Analytics Overview',
                'content' => 'Core KPIs, dashboards, and data-driven decision support.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'content', 'course_id', 'video_url', 'quiz', 'exercise', 'updated_at']);

        DB::table('assignments')->upsert([
            [
                'id' => 1,
                'module_id' => 'cs101-sem1-1',
                'course_id' => 'cs101',
                'title' => 'Digital Literacy Reflection',
                'description' => 'Reflect on how digital systems shape your daily workflow.',
                'instructions' => 'Write 500-700 words. Include two real-world examples and one improvement idea.',
                'assignment_type' => 'reflection',
                'max_points' => 20,
                'due_date' => now()->addDays(7),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'module_id' => 'cs101-sem1-2',
                'course_id' => 'cs101',
                'title' => 'Python Basics Lab',
                'description' => 'Complete the lab tasks on variables, input/output, and conditionals.',
                'instructions' => 'Submit a short write-up plus a link to your code repository.',
                'assignment_type' => 'lab',
                'max_points' => 30,
                'due_date' => now()->addDays(10),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'module_id' => 'cs101-sem1-3',
                'course_id' => 'cs101',
                'title' => 'Discrete Math Problem Set',
                'description' => 'Solve the first 10 problems in the provided worksheet.',
                'instructions' => 'Upload a PDF or share a drive link with your solutions.',
                'assignment_type' => 'problem-set',
                'max_points' => 25,
                'due_date' => now()->addDays(14),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'module_id' => 'cs101-sem1-4',
                'course_id' => 'cs101',
                'title' => 'AI Ethics Essay',
                'description' => 'Analyze an AI ethics case study and propose safeguards.',
                'instructions' => '800-1000 words. Cite at least 2 sources.',
                'assignment_type' => 'essay',
                'max_points' => 40,
                'due_date' => now()->addDays(18),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'module_id' => 'cs101-sem1-5',
                'course_id' => 'cs101',
                'title' => 'Professional Portfolio Draft',
                'description' => 'Create a draft student portfolio with your goals, skills, and project outline.',
                'instructions' => 'Submit a PDF or live link to your portfolio page.',
                'assignment_type' => 'portfolio',
                'max_points' => 15,
                'due_date' => now()->addDays(20),
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'description', 'instructions', 'assignment_type', 'max_points', 'due_date', 'status', 'module_id', 'course_id', 'updated_at']);

        DB::table('exam_questions')->upsert([
            [
                'id' => 1,
                'course_id' => 'cs101',
                'semester' => 1,
                'question' => 'Which of these is NOT a core component of a computer system?',
                'options' => json_encode(['CPU', 'RAM', 'Mouse', 'Hard Drive']),
                'answer' => 'Mouse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'course_id' => 'cs101',
                'semester' => 1,
                'question' => 'What does the if statement do in Python?',
                'options' => json_encode([
                    'Loops over a sequence',
                    'Defines a function',
                    'Makes a decision based on a condition',
                    'Prints output to the console',
                ]),
                'answer' => 'Makes a decision based on a condition',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'course_id' => 'cs101',
                'semester' => 1,
                'question' => 'Which of the following is a key application of AI?',
                'options' => json_encode([
                    'Creating spreadsheets',
                    'Natural Language Processing',
                    'Sending emails',
                    'Basic arithmetic',
                ]),
                'answer' => 'Natural Language Processing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['question', 'options', 'answer', 'course_id', 'semester', 'updated_at']);

        DB::table('job_postings')->upsert([
            ['id' => 'j1', 'title' => 'Software Engineer Intern', 'company' => 'TechCorp', 'location' => 'Remote', 'type' => 'Internship', 'description' => 'Join the engineering team to build student-facing products.', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'j2', 'title' => 'Registered Nurse', 'company' => 'HealthFirst Hospital', 'location' => 'New York, NY', 'type' => 'Full-time', 'description' => 'Support patient care in a clinical environment.', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'j3', 'title' => 'Business Analyst', 'company' => 'FinancePro', 'location' => 'London, UK', 'type' => 'Full-time', 'description' => 'Analyze KPIs and business performance.', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'j4', 'title' => 'Frontend Developer', 'company' => 'Innovate Solutions', 'location' => 'Remote', 'type' => 'Full-time', 'description' => 'Build UI components and improve accessibility.', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['title', 'company', 'location', 'type', 'description', 'updated_at']);

        DB::table('research_opportunities')->upsert([
            ['id' => 'r1', 'title' => 'AI in Medical Diagnosis', 'company' => 'HealthFirst Hospital', 'description' => 'Investigating ML models to improve diagnostic accuracy.', 'field' => 'Healthcare AI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'r2', 'title' => 'Next-Gen UI/UX with AI', 'company' => 'Innovate Solutions', 'description' => 'Researching adaptive and personalized user interfaces.', 'field' => 'Human-Computer Interaction', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'r3', 'title' => 'Financial Infrastructure Protocols', 'company' => 'AftaCoin', 'description' => 'Analyzing security and scalability of financial infrastructure.', 'field' => 'FinTech', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['title', 'company', 'description', 'field', 'updated_at']);

        DB::table('discussions')->upsert([
            [
                'id' => 'd1',
                'title' => 'Best resources for learning React?',
                'author' => 'Jane Doe',
                'avatar' => 'https://i.pravatar.cc/40?u=a042581f4e29026704d',
                'snippet' => 'I am new to frontend development and trying to pick up React. What are the best tutorials?',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'id' => 'd2',
                'title' => 'Tips for clinical rotations in nursing school',
                'author' => 'John Smith',
                'avatar' => 'https://i.pravatar.cc/40?u=a042581f4e29026705d',
                'snippet' => 'My first clinical rotation is coming up and I am feeling nervous. Any advice?',
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
        ], ['id'], ['title', 'author', 'avatar', 'snippet', 'updated_at']);

        DB::table('discussion_comments')->upsert([
            [
                'id' => 1,
                'discussion_id' => 'd1',
                'author' => 'John Smith',
                'avatar' => 'https://i.pravatar.cc/40?u=a042581f4e29026705d',
                'content' => 'Scrimba and the official docs are a good pairing.',
                'upvotes' => 12,
                'created_at' => now()->subHour(),
                'updated_at' => now()->subHour(),
            ],
            [
                'id' => 2,
                'discussion_id' => 'd1',
                'author' => 'Emily White',
                'avatar' => 'https://i.pravatar.cc/40?u=a042581f4e29026706d',
                'content' => 'Egghead has short, focused lessons.',
                'upvotes' => 5,
                'created_at' => now()->subMinutes(45),
                'updated_at' => now()->subMinutes(45),
            ],
        ], ['id'], ['content', 'upvotes', 'updated_at']);

        DB::table('consultant_applications')->upsert([
            [
                'id' => 'app1',
                'name' => 'Dr. Evelyn Reed',
                'department' => 'School of ICT',
                'status' => 'Pending',
                'avatar' => 'https://i.pravatar.cc/80?u=lecturer',
                'documents' => json_encode(['cv' => '#', 'id' => '#']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'app2',
                'name' => 'Prof. Alan Turing',
                'department' => 'School of Engineering',
                'status' => 'Pending',
                'avatar' => 'https://i.pravatar.cc/80?u=prof-turing',
                'documents' => json_encode(['cv' => '#', 'id' => '#']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['status', 'department', 'avatar', 'documents', 'updated_at']);

        DB::table('lecturer_applications')->upsert([
            [
                'id' => 1,
                'full_name' => 'Dr. Kelvin M.',
                'email' => 'kelvin.mwamba@email.com',
                'phone' => '+260 977 123456',
                'department' => 'School of ICT',
                'specialization' => 'Software Engineering',
                'highest_qualification' => 'PhD Computer Science',
                'years_experience' => 6,
                'program_interest' => 'cs101',
                'documents' => json_encode(['cv' => '#', 'certificates' => '#']),
                'status' => 'submitted',
                'submitted_at' => now()->subDay(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['status', 'updated_at']);

        DB::table('badges')->upsert([
            ['id' => 'b1', 'title' => 'Module Master', 'description' => 'Complete your first module.', 'icon' => 'award', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'b2', 'title' => 'Top Performer', 'description' => 'Achieve over 90% in an exam.', 'icon' => 'star', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'b3', 'title' => 'Course Completer', 'description' => 'Finish an entire course program.', 'icon' => 'book', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 'b4', 'title' => 'Community Helper', 'description' => 'Receive 10 upvotes on a comment.', 'icon' => 'users', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['title', 'description', 'icon', 'updated_at']);

        DB::table('leaderboard_entries')->upsert([
            ['id' => 1, 'rank' => 1, 'name' => 'Premium Student', 'avatar' => 'https://i.pravatar.cc/80?u=student-premium', 'school' => 'School of ICT', 'points' => 1250, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'rank' => 2, 'name' => 'Alice Johnson', 'avatar' => 'https://i.pravatar.cc/80?u=alice', 'school' => 'School of Business', 'points' => 1180, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'rank' => 3, 'name' => 'Bob Williams', 'avatar' => 'https://i.pravatar.cc/80?u=bob', 'school' => 'School of Engineering', 'points' => 1120, 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['rank', 'name', 'avatar', 'school', 'points', 'updated_at']);

        DB::table('applications')->upsert([
            [
                'id' => 1,
                'reference' => 'app-1001',
                'full_name' => 'Noria Banda',
                'email' => 'noria.banda@email.com',
                'program_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'school_id' => 'ict',
                'status' => 'offer_sent',
                'submitted_at' => now()->subDay(),
                'subject_points' => json_encode([
                    'english-language' => '6',
                    'mathematics' => '5',
                    'biology' => '5',
                    'chemistry' => '5',
                    'physics' => '6',
                    'computer-studies' => '5',
                    'civic-education' => '4',
                ]),
                'subject_count' => 7,
                'total_points' => 42,
                'delivery_mode' => 'hybrid',
                'learning_style' => 'traditional',
                'study_pace' => 'standard',
                'country' => 'Zambia',
                'notes' => 'Strong STEM profile. Recommend admission.',
                'offer_letter_message' => 'Congratulations! Your offer is ready. Please accept to continue enrollment.',
                'offer_issued_at' => now()->subHours(6),
                'admission_fee_paid' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'reference' => 'app-1002',
                'full_name' => 'Isaac Mwila',
                'email' => 'isaac.mwila@email.com',
                'program_id' => 'bus301',
                'intake_id' => null,
                'school_id' => 'business',
                'status' => 'submitted',
                'submitted_at' => now()->subDays(2),
                'subject_points' => json_encode([
                    'english-language' => '5',
                    'mathematics' => '4',
                    'commerce' => '5',
                    'geography' => '5',
                    'history' => '5',
                    'principles-of-accounts' => '5',
                ]),
                'subject_count' => 6,
                'total_points' => 34,
                'delivery_mode' => 'online',
                'learning_style' => 'personalized',
                'study_pace' => 'flex',
                'country' => 'Zambia',
                'notes' => 'Meets minimum criteria. Awaiting fee payment.',
                'offer_letter_message' => null,
                'offer_issued_at' => null,
                'admission_fee_paid' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['status', 'notes', 'updated_at']);

        $sampleApplicationId = DB::table('applications')->where('reference', 'app-1001')->value('id');
        if ($sampleApplicationId) {
            DB::table('application_documents')->upsert([
                [
                    'id' => 1,
                    'application_id' => $sampleApplicationId,
                    'document_type' => 'national_id',
                    'file_name' => 'national-id.pdf',
                    'file_path' => 'admissions/app-1001/national-id.pdf',
                    'mime_type' => 'application/pdf',
                    'file_size' => 102400,
                    'status' => 'verified',
                    'review_notes' => 'Verified NRC copy.',
                    'created_at' => now()->subDay(),
                    'updated_at' => now()->subDay(),
                ],
                [
                    'id' => 2,
                    'application_id' => $sampleApplicationId,
                    'document_type' => 'certified_results',
                    'file_name' => 'results.pdf',
                    'file_path' => 'admissions/app-1001/results.pdf',
                    'mime_type' => 'application/pdf',
                    'file_size' => 204800,
                    'status' => 'uploaded',
                    'review_notes' => null,
                    'created_at' => now()->subDay(),
                    'updated_at' => now()->subDay(),
                ],
            ], ['id'], ['status', 'review_notes', 'updated_at']);
        }

        $adminId = DB::table('users')->where('email', 'admin@univai.edu')->value('id');
        $lecturerId = DB::table('users')->where('email', 'lecturer@univai.edu')->value('id');
        $lecturerAId = DB::table('users')->where('email', 'lecturer.a@univai.edu')->value('id');
        $lecturerBId = DB::table('users')->where('email', 'lecturer.b@univai.edu')->value('id');
        $studentId = DB::table('users')->where('email', 'student.premium@univai.edu')->value('id');

        if ($studentId) {
            DB::table('assignment_submissions')->upsert([
                [
                    'id' => 1,
                    'assignment_id' => 1,
                    'student_id' => $studentId,
                    'submitted_at' => now()->subDays(1),
                    'content' => 'Reflection draft on digital systems and productivity tools.',
                    'attachment_url' => 'https://drive.google.com/example/reflection',
                    'status' => 'graded',
                    'grade' => 18.5,
                    'feedback' => 'Strong reflection and examples. Add one more source for a higher score.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 2,
                    'assignment_id' => 2,
                    'student_id' => $studentId,
                    'submitted_at' => now()->subHours(6),
                    'content' => 'Python lab solutions with short explanation.',
                    'attachment_url' => 'https://github.com/univai-demo/python-basics-lab',
                    'status' => 'submitted',
                    'grade' => null,
                    'feedback' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ], ['id'], ['submitted_at', 'content', 'attachment_url', 'status', 'grade', 'feedback', 'updated_at']);
        }

        if ($lecturerId) {
            DB::table('lesson_documents')->upsert([
                [
                    'id' => 1,
                    'lesson_id' => 'l1-cs101',
                    'intake_id' => 'cs101-2026-jan',
                    'source' => 'manual',
                    'status' => 'approved',
                    'uploaded_by' => $lecturerId,
                    'approved_by' => $lecturerId,
                    'approved_at' => now()->subDays(2),
                    'file_name' => 'Digital Systems Notes.pdf',
                    'mime_type' => 'application/pdf',
                    'storage_path' => 'seeded/digital-systems-notes.pdf',
                    'extracted_text' => 'Summary of hardware, software, and network components. Includes diagrams and key definitions.',
                    'review_notes' => 'Approved for intake distribution.',
                    'created_at' => now()->subDays(3),
                    'updated_at' => now()->subDays(2),
                ],
                [
                    'id' => 2,
                    'lesson_id' => 'l3-cs101',
                    'intake_id' => 'cs101-2026-jan',
                    'source' => 'manual',
                    'status' => 'pending',
                    'uploaded_by' => $lecturerAId ?? $lecturerId,
                    'approved_by' => null,
                    'approved_at' => null,
                    'file_name' => 'Python Lab Outline.txt',
                    'mime_type' => 'text/plain',
                    'storage_path' => null,
                    'extracted_text' => 'Lab checklist: input/output, conditions, loops, and debugging steps.',
                    'review_notes' => null,
                    'created_at' => now()->subDay(),
                    'updated_at' => now()->subDay(),
                ],
                [
                    'id' => 3,
                    'lesson_id' => 'l1-bus301',
                    'intake_id' => 'bus301-2026-jan',
                    'source' => 'manual',
                    'status' => 'approved',
                    'uploaded_by' => $lecturerAId ?? $lecturerId,
                    'approved_by' => $lecturerAId ?? $lecturerId,
                    'approved_at' => now()->subHours(12),
                    'file_name' => 'Strategic Leadership Brief.md',
                    'mime_type' => 'text/markdown',
                    'storage_path' => 'seeded/strategic-leadership-brief.md',
                    'extracted_text' => 'Leadership models, decision frameworks, and stakeholder alignment notes.',
                    'review_notes' => 'Approved with minor edits.',
                    'created_at' => now()->subDay(),
                    'updated_at' => now()->subHours(12),
                ],
            ], ['id'], ['lesson_id', 'intake_id', 'status', 'approved_by', 'approved_at', 'file_name', 'mime_type', 'storage_path', 'extracted_text', 'review_notes', 'updated_at']);
        }

        DB::table('enrollments')->upsert([
            [
                'user_id' => $studentId,
                'intake_id' => 'cs101-2026-jan',
                'status' => 'active',
                'enrolled_at' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['user_id', 'intake_id'], ['status', 'enrolled_at', 'updated_at']);

        DB::table('course_lecturer_assignments')->upsert([
            [
                'course_id' => 'cs101',
                'module_id' => 'cs101-sem1-1',
                'lecturer_id' => $lecturerId,
                'intake_id' => 'cs101-2026-jan',
                'role' => 'lead',
                'assigned_by' => $adminId,
                'meeting_provider' => 'google-meet',
                'meeting_url' => 'https://meet.google.com/xyz-demo',
                'meeting_schedule' => json_encode(['day' => 'Wednesday', 'time' => '10:00 AM']),
                'meeting_notes' => 'Weekly live session. Join 5 minutes early.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'cs101',
                'module_id' => 'cs101-sem1-2',
                'lecturer_id' => $lecturerAId,
                'intake_id' => 'cs101-2026-jan',
                'role' => 'assistant',
                'assigned_by' => $adminId,
                'meeting_provider' => 'zoom',
                'meeting_url' => 'https://zoom.us/j/123456789',
                'meeting_schedule' => json_encode(['day' => 'Tuesday', 'time' => '14:00 PM']),
                'meeting_notes' => 'Lab focus sessions for Python fundamentals.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'cs101',
                'module_id' => 'cs101-sem1-3',
                'lecturer_id' => $lecturerBId,
                'intake_id' => 'cs101-2026-jan',
                'role' => 'lead',
                'assigned_by' => $adminId,
                'meeting_provider' => 'google-meet',
                'meeting_url' => 'https://meet.google.com/abc-math',
                'meeting_schedule' => json_encode(['day' => 'Thursday', 'time' => '11:00 AM']),
                'meeting_notes' => 'Problem-solving workshops every Thursday.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'bus301',
                'module_id' => 'bus301-sem1-1',
                'lecturer_id' => $lecturerAId,
                'intake_id' => 'bus301-2026-jan',
                'role' => 'lead',
                'assigned_by' => $adminId,
                'meeting_provider' => 'microsoft-teams',
                'meeting_url' => 'https://teams.microsoft.com/l/meetup-join/demo',
                'meeting_schedule' => json_encode(['day' => 'Saturday', 'time' => '09:00 AM']),
                'meeting_notes' => 'Weekend intensive session for MBA cohort.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['course_id', 'lecturer_id', 'intake_id'], ['role', 'assigned_by', 'meeting_provider', 'meeting_url', 'meeting_schedule', 'meeting_notes', 'updated_at']);

        DB::table('course_sessions')->upsert([
            [
                'id' => 1,
                'course_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'title' => 'Intro Lecture - Digital Systems',
                'session_type' => 'lecture',
                'day_of_week' => 'Wednesday',
                'start_time' => '10:00:00',
                'end_time' => '11:30:00',
                'location' => 'Room A1',
                'meeting_url' => 'https://meet.google.com/xyz-demo',
                'created_by' => $lecturerId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'course_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'title' => 'Programming Fundamentals Lab',
                'session_type' => 'lab',
                'day_of_week' => 'Friday',
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'location' => 'Lab 2',
                'meeting_url' => 'https://meet.google.com/xyz-demo',
                'created_by' => $lecturerId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'course_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'title' => 'AI Ethics Workshop',
                'session_type' => 'workshop',
                'day_of_week' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'location' => 'Room B3',
                'meeting_url' => 'https://meet.google.com/xyz-demo',
                'created_by' => $lecturerId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'course_id' => 'cs101',
                'intake_id' => 'cs101-2026-jan',
                'title' => 'Project Clinic',
                'session_type' => 'tutorial',
                'day_of_week' => 'Thursday',
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'location' => 'Room A2',
                'meeting_url' => 'https://meet.google.com/xyz-demo',
                'created_by' => $lecturerId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['title', 'session_type', 'day_of_week', 'start_time', 'end_time', 'location', 'meeting_url', 'updated_at']);

        if ($studentId) {
            DB::table('course_attempts')->upsert([
                [
                    'id' => 1,
                    'student_id' => $studentId,
                    'module_id' => 'cs101-sem1-1',
                    'intake_id' => 'cs101-2026-jan',
                    'attempt_no' => 1,
                    'final_percentage' => 78,
                    'exam_score' => 72,
                    'letter_grade' => 'B',
                    'grade_points' => 3.0,
                    'credits_attempted' => 6,
                    'credits_earned' => 6,
                    'status' => 'pass',
                    'result_status' => 'published',
                    'recorded_by' => $lecturerId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ], ['id'], ['final_percentage', 'exam_score', 'letter_grade', 'grade_points', 'credits_attempted', 'credits_earned', 'status', 'result_status', 'updated_at']);
        }

        DB::table('route_change_requests')->upsert([
            [
                'id' => 1,
                'student_id' => $studentId,
                'current_intake_id' => 'cs101-2026-jan',
                'requested_intake_id' => 'cs101-2026-jun',
                'reason' => 'Need a more flexible online schedule.',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['status', 'updated_at']);

        DB::table('invoices')->upsert([
            [
                'id' => 1,
                'student_id' => $studentId,
                'intake_id' => 'cs101-2026-jan',
                'title' => 'Semester 1 Tuition',
                'amount' => 650,
                'paid_amount' => 0,
                'status' => 'unpaid',
                'due_date' => now()->addDays(20)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id'], ['status', 'paid_amount', 'updated_at']);

        DB::table('dashboard_metrics')->upsert([
            ['role' => 'admin', 'key' => 'revenue', 'label' => 'Total Revenue', 'value' => '$45,231.89', 'note' => '+20.1% from last month', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'admin', 'key' => 'students', 'label' => 'Total Students', 'value' => '1,254', 'note' => '+180.1% from last month', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'admin', 'key' => 'courses', 'label' => 'Total Courses', 'value' => '150', 'note' => '+10 new courses this week', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'admin', 'key' => 'activity', 'label' => 'Platform Activity', 'value' => '+573', 'note' => 'New engagements today', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'lecturer', 'key' => 'courses', 'label' => 'Courses Taught', 'value' => '2', 'note' => 'Active this semester', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'lecturer', 'key' => 'students', 'label' => 'Total Students', 'value' => '77', 'note' => 'Across all courses', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'lecturer', 'key' => 'messages', 'label' => 'Unread Messages', 'value' => '12', 'note' => 'From students', 'created_at' => now(), 'updated_at' => now()],
            ['role' => 'student', 'key' => 'wallet', 'label' => 'AFTA Balance', 'value' => '925 AFTA', 'note' => 'AFTACOIN Balance', 'created_at' => now(), 'updated_at' => now()],
        ], ['role', 'key'], ['label', 'value', 'note', 'updated_at']);

        DB::table('course_metrics')->upsert([
            ['course_id' => 'cs101', 'student_count' => 48, 'avg_progress' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['course_id' => 'nur201', 'student_count' => 36, 'avg_progress' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['course_id' => 'bus301', 'student_count' => 28, 'avg_progress' => 43, 'created_at' => now(), 'updated_at' => now()],
        ], ['course_id'], ['student_count', 'avg_progress', 'updated_at']);

        DB::table('student_actions')->upsert([
            ['id' => 1, 'title' => 'Resume last lesson', 'description' => 'Continue where you left off.', 'href' => '/student/lessons/l1-cs101', 'priority' => 1, 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'title' => 'Submit assignment', 'description' => '2 items due this week.', 'href' => '/student/assignments', 'priority' => 2, 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'title' => 'Book upcoming exam', 'description' => 'Reserve your seat early.', 'href' => '/student/exams/bookings', 'priority' => 3, 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'title' => 'Review study plan', 'description' => 'Personalized weekly schedule.', 'href' => '/student/study-plan', 'priority' => 4, 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['title', 'description', 'href', 'priority', 'role', 'updated_at']);

        DB::table('student_deadlines')->upsert([
            ['id' => 1, 'title' => 'Digital Literacy Reflection', 'type' => 'Assignment', 'due_date' => now()->addDays(7)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'title' => 'Python Basics Lab', 'type' => 'Assignment', 'due_date' => now()->addDays(10)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'title' => 'Discrete Math Problem Set', 'type' => 'Assignment', 'due_date' => now()->addDays(14)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'title' => 'Semester 1 Exam', 'type' => 'Exam', 'due_date' => now()->addDays(9)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'title' => 'Lab Session Check-in', 'type' => 'Virtual Lab', 'due_date' => now()->addDays(4)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'title' => 'AI Ethics Essay', 'type' => 'Assignment', 'due_date' => now()->addDays(18)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'title' => 'Portfolio Draft', 'type' => 'Assignment', 'due_date' => now()->addDays(20)->toDateString(), 'role' => 'premium-student', 'created_at' => now(), 'updated_at' => now()],
        ], ['id'], ['title', 'type', 'due_date', 'role', 'updated_at']);

        if ($studentId) {
            DB::table('wallet_settings')->updateOrInsert(
                ['user_id' => $studentId],
                [
                    'wallet_address' => '0xAFTA1234DEMO',
                    'payout_currency' => 'AFTA',
                    'status' => 'pending',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );

            DB::table('payment_methods')->upsert([
                [
                    'id' => 1,
                    'user_id' => $studentId,
                    'type' => 'card',
                    'provider' => 'Visa',
                    'last4' => '4242',
                    'expiry_month' => 12,
                    'expiry_year' => 2027,
                    'is_default' => true,
                    'status' => 'active',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ], ['id'], ['provider', 'last4', 'expiry_month', 'expiry_year', 'is_default', 'status', 'updated_at']);

            DB::table('scholarship_applications')->upsert([
                [
                    'id' => 1,
                    'user_id' => $studentId,
                    'program_id' => 'cs101',
                    'statement' => 'Requesting aid due to family financial constraints while maintaining a 3.4 GPA.',
                    'status' => 'submitted',
                    'submitted_at' => now()->subDay(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ], ['id'], ['status', 'statement', 'submitted_at', 'updated_at']);

            DB::table('portfolio_items')->upsert([
                [
                    'id' => 1,
                    'user_id' => $studentId,
                    'title' => 'Smart Attendance Tracker',
                    'description' => 'Built a QR-based attendance app with analytics dashboards.',
                    'link' => 'https://github.com/univai-demo/attendance-tracker',
                    'item_type' => 'project',
                    'status' => 'draft',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ], ['id'], ['title', 'description', 'link', 'status', 'updated_at']);

            DB::table('support_tickets')->upsert([
                [
                    'id' => 'ticket-001',
                    'user_id' => $studentId,
                    'email' => 'student.premium@univai.edu',
                    'subject' => 'Module unlock request',
                    'description' => 'Requesting access to the next module after completing prerequisites.',
                    'category' => 'Academic Guidance',
                    'priority' => 'normal',
                    'status' => 'open',
                    'created_at' => now()->subHours(6),
                    'updated_at' => now()->subHours(6),
                ],
            ], ['id'], ['status', 'updated_at']);

            DB::table('support_messages')->upsert([
                [
                    'id' => 1,
                    'ticket_id' => 'ticket-001',
                    'user_id' => $studentId,
                    'author' => 'Premium Student',
                    'role' => 'student',
                    'message' => 'Completed CS101 assessments. Please unlock the next module.',
                    'created_at' => now()->subHours(6),
                    'updated_at' => now()->subHours(6),
                ],
            ], ['id'], ['message', 'updated_at']);
        }

        DB::table('research_applications')->upsert([
            [
                'id' => 1,
                'research_id' => 'r1',
                'full_name' => 'Premium Student',
                'email' => 'student.premium@univai.edu',
                'experience' => 'Completed AI foundations and built a diagnosis prototype.',
                'availability' => '8 hours/week',
                'status' => 'submitted',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
        ], ['id'], ['status', 'updated_at']);
    }
}
