import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const aisControlAccountingTables: AccountingTableTemplate[] = [
  table('accounting_system_flowchart_table', 'Accounting system flowchart table', 'advanced', 'AIS / internal controls', 'case_study', 'Narrative table version of accounting system flow from source document to ledger/report.', { tableKind: 'accounting_system_flowchart', columns: ['Step', 'Input/document', 'Process', 'Output/control'], rows: [['1', 'Sales order', 'Approve customer order', 'Approved order'], ['2', 'Delivery note', 'Dispatch goods', 'Signed delivery note'], ['3', 'Sales invoice', 'Record sale', 'Invoice posted to ledger']], required: ['Map system flow', 'Identify control points'] }),
  table('document_flow_table', 'Document flow table', 'advanced', 'AIS / internal controls', 'case_study', 'Tracks documents across departments and systems.', { tableKind: 'document_flow', columns: ['Document', 'Origin', 'Destination', 'Purpose', 'Control'], rows: [['Purchase requisition', 'Stores', 'Procurement', 'Request goods', 'Authorisation'], ['Goods received note', 'Receiving', 'Accounts payable', 'Confirm receipt', 'Match to invoice']], required: ['Trace documents', 'Identify missing controls'] }),
  table('transaction_cycle_control_matrix', 'Internal control matrix by transaction cycle', 'advanced', 'AIS / internal controls', 'case_study', 'Control objectives, risks, controls, and tests by transaction cycle.', { tableKind: 'transaction_cycle_control_matrix', columns: ['Cycle', 'Risk', 'Control objective', 'Control activity', 'Test'], rows: [['Revenue', 'Fictitious sales', 'Occurrence', 'Approve credit sales and match dispatch', 'Inspect approved orders'], ['Purchases', 'Unauthorised purchases', 'Authorisation', 'PO approval workflow', 'Review purchase approvals']], required: ['Identify risks', 'Map controls and tests'] }),
  table('revenue_cycle_table', 'Revenue cycle table', 'advanced', 'AIS / internal controls', 'case_study', 'Revenue cycle events, documents, accounts, and controls.', { tableKind: 'revenue_cycle', columns: ['Event', 'Document', 'Accounts affected', 'Control'], rows: [['Receive order', 'Sales order', 'None', 'Credit approval'], ['Dispatch goods', 'Delivery note', 'Inventory/COGS', 'Dispatch authorisation'], ['Invoice customer', 'Sales invoice', 'Receivables/Sales', 'Invoice sequence check']], required: ['Map revenue cycle', 'Identify accounting entries and controls'] }),
  table('purchases_payables_cycle_table', 'Purchases/payables cycle table', 'advanced', 'AIS / internal controls', 'case_study', 'Purchases cycle events, documents, accounts, and controls.', { tableKind: 'purchases_payables_cycle', columns: ['Event', 'Document', 'Accounts affected', 'Control'], rows: [['Request goods', 'Purchase requisition', 'None', 'Budget approval'], ['Order goods', 'Purchase order', 'Commitment', 'Approved supplier list'], ['Receive goods', 'GRN', 'Inventory/accrual', 'Three-way match']], required: ['Map purchases cycle', 'Identify controls'] }),
  table('payroll_cycle_table', 'Payroll cycle table', 'advanced', 'AIS / internal controls', 'case_study', 'Payroll cycle from employee master file to payslip and deductions.', { tableKind: 'payroll_cycle', columns: ['Event', 'Data/document', 'Risk', 'Control'], rows: [['Add employee', 'Employee master file', 'Ghost employee', 'HR authorisation'], ['Record time', 'Timesheet', 'Inflated hours', 'Supervisor approval'], ['Run payroll', 'Payroll register', 'Incorrect deductions', 'Payroll review']], required: ['Map payroll risks', 'Recommend controls'] }),
  table('inventory_cycle_table', 'Inventory cycle table', 'advanced', 'AIS / internal controls', 'case_study', 'Inventory cycle from purchase to storage, issue, count, and adjustment.', { tableKind: 'inventory_cycle', columns: ['Stage', 'Document/system record', 'Risk', 'Control'], rows: [['Receive goods', 'GRN', 'Wrong quantity', 'Independent count'], ['Store goods', 'Bin card', 'Theft/damage', 'Restricted access'], ['Issue goods', 'Stores requisition', 'Unauthorised issue', 'Approved requisition']], required: ['Map inventory controls', 'Identify weak points'] }),
  table('system_access_control_matrix', 'System access control matrix', 'advanced', 'AIS / internal controls', 'case_study', 'Role-based access controls for accounting systems.', { tableKind: 'system_access_control_matrix', columns: ['Role', 'Create vendor', 'Approve PO', 'Post invoice', 'Release payment', 'Risk'], rows: [['Procurement officer', 'No', 'Create PO only', 'No', 'No', 'Limited risk'], ['Accounts payable clerk', 'No', 'No', 'Yes', 'No', 'Posting errors'], ['Finance manager', 'No', 'Approve', 'Review', 'Yes', 'High privilege']], required: ['Check segregation of duties', 'Identify excessive access'] }),
  table('audit_trail_review_table', 'Audit trail review table', 'advanced', 'AIS / internal controls', 'case_study', 'Reviews system logs for user, action, timestamp, approval, and exception.', { tableKind: 'audit_trail_review', columns: ['User', 'Action', 'Timestamp', 'Approval/reference', 'Exception?'], rows: [['apclerk01', 'Posted supplier invoice', '2026-01-05 10:30', 'PO101/GRN44', 'No'], ['admin01', 'Changed supplier bank details', '2026-01-06 22:15', 'None', 'Yes']], required: ['Review audit trail', 'Identify suspicious activity'] }),
  table('erp_posting_flow_table', 'ERP posting flow table', 'advanced', 'AIS / internal controls', 'case_study', 'ERP posting flow from subledger to general ledger and reporting.', { tableKind: 'erp_posting_flow', columns: ['Module', 'Source transaction', 'Subledger posting', 'GL posting', 'Report impact'], rows: [['Sales', 'Invoice', 'Customer account Dr', 'Receivables Dr / Sales Cr', 'Revenue and receivables'], ['Inventory', 'Goods issue', 'Inventory movement', 'COGS Dr / Inventory Cr', 'Profit and inventory'], ['Payroll', 'Payroll run', 'Employee payslip', 'Wages Dr / Payables Cr', 'Expenses and liabilities']], required: ['Trace ERP posting', 'Explain report impact'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
