import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const auditAccountingTables: AccountingTableTemplate[] = [
  table('audit_strategy_memo_table', 'Audit strategy memorandum table', 'professional', 'Audit', 'audit_risk', 'Summarises audit scope, strategy, risk focus, team, timing, and reporting plan.', { evidenceStandard: 'Audit strategy aligned to risk and materiality.', tableKind: 'audit_strategy_memo', columns: ['Area', 'Decision/assessment', 'Rationale'], rows: [['Scope', 'Full statutory audit', 'Annual financial statements'], ['Risk focus', 'Revenue, inventory, cash', 'High inherent/control risk'], ['Team', 'Senior + two assistants', 'Complex inventory count']], required: ['Define audit strategy', 'Link strategy to risk'] }),
  table('audit_planning_checklist', 'Audit planning checklist', 'professional', 'Audit', 'audit_risk', 'Planning checklist for engagement acceptance, independence, materiality, risk, and audit timetable.', { tableKind: 'audit_planning_checklist', columns: ['Planning step', 'Completed?', 'Evidence/reference'], rows: [['Independence confirmed', 'Yes', 'Independence declaration'], ['Materiality set', 'Yes', 'Planning file A2'], ['Risk assessment completed', 'No', 'Pending management meeting']], required: ['Complete planning steps', 'Identify missing planning work'] }),
  table('audit_risk_register', 'Audit risk register', 'professional', 'Audit', 'audit_risk', 'Risk register with likelihood, impact, assertion, response, and owner.', { tableKind: 'audit_risk_register', columns: ['Risk', 'Likelihood', 'Impact', 'Assertion', 'Response'], rows: [['Revenue overstatement', 'High', 'High', 'Occurrence', 'Cut-off testing and contracts review'], ['Inventory obsolete', 'Medium', 'High', 'Valuation', 'NRV testing']], required: ['Assess likelihood and impact', 'Plan response'] }),
  table('fraud_risk_assessment', 'Fraud risk assessment table', 'professional', 'Audit', 'audit_risk', 'Fraud triangle assessment: pressure, opportunity, rationalisation, and audit response.', { tableKind: 'fraud_risk_assessment', columns: ['Fraud risk', 'Pressure', 'Opportunity', 'Rationalisation', 'Audit response'], rows: [['Revenue manipulation', 'Bonus target', 'Weak review controls', 'Market pressure', 'Journal testing and cut-off work']], required: ['Identify fraud risk factors', 'Design fraud response'] }),
  table('internal_control_questionnaire', 'Internal control questionnaire', 'professional', 'Audit', 'audit_risk', 'ICQ for evaluating design and operation of internal controls.', { tableKind: 'internal_control_questionnaire', columns: ['Question', 'Yes/No', 'Risk implication', 'Follow-up'], rows: [['Are receipts sequentially numbered?', 'No', 'Completeness risk', 'Perform sequence testing'], ['Are bank reconciliations reviewed?', 'Yes', 'Reduced cash risk', 'Inspect review evidence']], required: ['Evaluate controls', 'Plan follow-up testing'] }),
  table('walkthrough_test_table', 'Walkthrough test table', 'professional', 'Audit', 'audit_risk', 'Documents transaction walkthrough from initiation to recording.', { tableKind: 'walkthrough_test', columns: ['Stage', 'Document/control', 'Observation', 'Risk'], rows: [['Order', 'Approved customer order', 'Approval missing on sample', 'Unauthorised sale'], ['Dispatch', 'Delivery note', 'Matched to invoice', 'Low occurrence risk']], required: ['Trace transaction flow', 'Identify control gaps'] }),
  table('sampling_plan_table', 'Sampling plan table', 'professional', 'Audit', 'audit_risk', 'Sampling objective, population, method, sample size, and tolerable error.', { tableKind: 'sampling_plan', columns: ['Objective', 'Population', 'Method', 'Sample size', 'Tolerable error'], rows: [['Test revenue occurrence', 'Sales invoices', 'Random sample', '40', '5% deviation'], ['Test receivables existence', 'Customer balances', 'Monetary unit sampling', '30', 'K20,000']], required: ['Define population', 'Select sample method'] }),
  table('sampling_results_evaluation', 'Sampling results evaluation table', 'professional', 'Audit', 'audit_risk', 'Evaluates sample exceptions and projects misstatement/deviation.', { tableKind: 'sampling_results_evaluation', columns: ['Test', 'Sample size', 'Exceptions', 'Projected error', 'Conclusion'], rows: [['Revenue occurrence', '40', '2', '5% deviation', 'Within tolerable limit'], ['Inventory valuation', '30', '4', 'K28,000', 'Above tolerable error']], required: ['Evaluate sample results', 'Conclude on population'] }),
  table('analytical_procedures_expectation', 'Analytical procedures expectation table', 'professional', 'Audit', 'audit_risk', 'Develops expectation, actual result, variance, and follow-up procedure.', { tableKind: 'analytical_procedures_expectation', columns: ['Account', 'Expectation', 'Actual', 'Variance', 'Follow-up'], rows: [['Gross margin', '45%', '32%', '13% lower', 'Investigate pricing/cost errors'], ['Payroll', 'K600,000', 'K650,000', 'K50,000 higher', 'Compare headcount and rates']], required: ['Develop expectation', 'Investigate unusual variance'] }),
  table('going_concern_assessment', 'Going concern assessment table', 'professional', 'Audit', 'audit_risk', 'Assesses liquidity, financing, forecasts, and disclosure for going concern.', { tableKind: 'going_concern_assessment', columns: ['Indicator', 'Evidence', 'Severity', 'Audit response'], rows: [['Loan covenant breach', 'Bank letter', 'High', 'Review waiver/refinancing'], ['Negative cash flows', 'Cash forecast', 'Medium', 'Stress-test forecast']], required: ['Assess going concern risk', 'Plan audit response'] }),
  table('subsequent_events_review', 'Subsequent events review table', 'professional', 'Audit', 'audit_risk', 'Reviews subsequent events and determines adjusting/non-adjusting treatment.', { tableKind: 'subsequent_events_review', columns: ['Event', 'Date', 'Adjusting?', 'Audit action'], rows: [['Customer bankruptcy', 'After year-end', 'Yes if condition existed', 'Adjust receivable'], ['Fire after year-end', 'After year-end', 'No', 'Consider disclosure']], required: ['Classify events', 'State audit action'] }),
  table('written_representation_checklist', 'Written representation checklist', 'professional', 'Audit', 'audit_risk', 'Checklist of management representations required before audit report signing.', { tableKind: 'written_representation_checklist', columns: ['Representation area', 'Included?', 'Why needed'], rows: [['Completeness of liabilities', 'Yes', 'Management responsibility'], ['Related parties disclosed', 'No', 'Follow up before signing']], required: ['Identify required representations', 'Resolve missing items'] }),
  table('management_letter_points', 'Management letter points table', 'professional', 'Audit', 'audit_risk', 'Weakness, implication, recommendation, and management response table.', { tableKind: 'management_letter_points', columns: ['Weakness', 'Implication', 'Recommendation', 'Management response'], rows: [['No segregation of cash duties', 'Fraud/error risk', 'Separate custody and recording roles', 'To hire cashier'], ['Late bank reconciliations', 'Misstatement risk', 'Monthly review by manager', 'Agreed']], required: ['Draft management letter point', 'Recommend control improvement'] }),
  table('audit_completion_checklist', 'Audit completion checklist', 'professional', 'Audit', 'audit_risk', 'Completion checklist before signing: review, subsequent events, representations, report, file assembly.', { tableKind: 'audit_completion_checklist', columns: ['Completion step', 'Status', 'Reference'], rows: [['Final analytical review', 'Done', 'C1'], ['Subsequent events review', 'Pending', 'C2'], ['Management representation letter', 'Pending', 'C3']], required: ['Complete final audit procedures', 'Identify blockers to signing'] }),
  table('unadjusted_misstatement_summary', 'Unadjusted misstatement summary', 'professional', 'Audit', 'audit_risk', 'Summary of unadjusted misstatements compared to materiality.', { tableKind: 'unadjusted_misstatement_summary', columns: ['Misstatement', 'Debit/Credit effect', 'Amount', 'Management accepted?', 'Material?'], rows: [['Accrual omitted', 'Expense understated/liability understated', '8,000', 'No', 'No'], ['Inventory overstatement', 'Inventory/profit overstated', '25,000', 'No', 'Yes']], required: ['Aggregate unadjusted errors', 'Compare to materiality'] }),
  table('materiality_revision_table', 'Materiality revision table', 'professional', 'Audit', 'audit_risk', 'Revises planning materiality when actual results differ from expected benchmarks.', { tableKind: 'materiality_revision', columns: ['Benchmark', 'Planning estimate', 'Actual result', 'Original materiality', 'Revised materiality'], rows: [['Profit before tax', '500,000', '300,000', '25,000', '15,000']], required: ['Revise materiality', 'Assess effect on audit work'] }),
  table('component_group_audit_table', 'Component audit/group audit table', 'professional', 'Audit', 'audit_risk', 'Group audit component significance and work scope.', { tableKind: 'component_group_audit', columns: ['Component', 'Financial significance', 'Risk significance', 'Work required'], rows: [['Subsidiary A', 'High', 'Medium', 'Full scope audit'], ['Subsidiary B', 'Low', 'High fraud risk', 'Specific procedures']], required: ['Classify component', 'Plan component work'] }),
  table('isa_compliance_checklist', 'ISA compliance checklist', 'professional', 'Audit', 'audit_risk', 'Checklist mapping audit procedures to ISA compliance areas.', { tableKind: 'isa_compliance_checklist', columns: ['ISA area', 'Requirement', 'Evidence in file'], rows: [['Risk assessment', 'Understand entity and controls', 'Planning memo and ICQ'], ['Audit evidence', 'Sufficient appropriate evidence', 'Working papers and confirmations']], required: ['Map work to ISA requirement', 'Identify missing evidence'] }),
  table('ethics_independence_threats', 'Ethics/independence threats table', 'professional', 'Audit', 'audit_risk', 'Identifies ethical threats, safeguards, and conclusion.', { tableKind: 'ethics_independence_threats', columns: ['Threat', 'Example', 'Safeguard', 'Conclusion'], rows: [['Self-review', 'Firm prepared accounting records', 'Separate team/review partner', 'Threat reduced'], ['Familiarity', 'Long association with client', 'Partner rotation', 'Monitor']], required: ['Identify threat', 'Recommend safeguard'] }),
  table('quality_control_review_table', 'Quality control review table', 'professional', 'Audit', 'audit_risk', 'Engagement quality control review checklist and findings.', { tableKind: 'quality_control_review', columns: ['Review area', 'Finding', 'Resolved?', 'Reviewer comment'], rows: [['Materiality', 'Benchmark rationale weak', 'No', 'Add justification'], ['Going concern', 'Forecast not stress-tested', 'No', 'Perform sensitivity analysis']], required: ['Review audit quality', 'Resolve findings before signing'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
