import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const consolidationAccountingTables: AccountingTableTemplate[] = [
  table('detailed_goodwill_calculation', 'Goodwill calculation table — detailed version', 'advanced', 'Group accounts', 'consolidation', 'Detailed goodwill calculation using consideration, NCI, previous interest, and fair value of net assets.', { standardFramework: 'IFRS', tableKind: 'detailed_goodwill_calculation', columns: ['Item', 'Amount'], rows: [['Consideration transferred', '180,000'], ['NCI at acquisition', '40,000'], ['Fair value of previous interest', '0'], ['Less fair value of net assets acquired', '(190,000)'], ['Goodwill', '30,000']], required: ['Calculate goodwill', 'Explain each component'] }),
  table('consideration_transferred_analysis', 'Consideration transferred analysis table', 'advanced', 'Group accounts', 'consolidation', 'Analyses cash, shares, deferred consideration, contingent consideration, and acquisition costs.', { standardFramework: 'IFRS', tableKind: 'consideration_transferred', columns: ['Component', 'Treatment', 'Amount included in consideration'], rows: [['Cash paid', 'Include', '100,000'], ['Shares issued', 'Include at fair value', '60,000'], ['Deferred consideration', 'Include at present value', '20,000'], ['Professional fees', 'Expense, not consideration', '0']], required: ['Classify consideration items', 'Calculate consideration transferred'] }),
  table('fair_value_adjustment_depreciation', 'Fair value adjustment depreciation table', 'advanced', 'Group accounts', 'consolidation', 'Calculates extra depreciation arising from fair value uplift at acquisition.', { standardFramework: 'IFRS', tableKind: 'fair_value_adjustment_depreciation', columns: ['Asset', 'FV uplift', 'Remaining useful life', 'Annual extra depreciation', 'Post-acquisition years', 'Accumulated adjustment'], rows: [['Equipment', '20,000', '5 years', '4,000', '2', '8,000']], required: ['Calculate extra depreciation', 'Adjust group retained earnings'] }),
  table('intragroup_current_account_reconciliation', 'Intra-group current account reconciliation', 'advanced', 'Group accounts', 'consolidation', 'Reconciles parent and subsidiary current accounts before elimination.', { standardFramework: 'IFRS', tableKind: 'intragroup_current_account_reconciliation', columns: ['Item', 'Parent records', 'Subsidiary records', 'Adjustment'], rows: [['Current account balance', '25,000 receivable', '22,000 payable', '3,000 cash in transit'], ['Goods in transit', '', '', '2,000'], ['Final balance for elimination', '27,000', '27,000', 'Eliminate']], required: ['Reconcile current accounts', 'Prepare elimination adjustment'] }),
  table('intragroup_sales_elimination_detailed', 'Intra-group sales elimination table — detailed', 'advanced', 'Group accounts', 'consolidation', 'Eliminates intragroup sales, purchases, and unrealised profit.', { standardFramework: 'IFRS', tableKind: 'intragroup_sales_elimination', columns: ['Transaction', 'Seller', 'Buyer', 'Amount', 'Adjustment'], rows: [['Intra-group sale', 'Parent', 'Subsidiary', '50,000', 'Dr Sales Cr Cost of sales'], ['Unrealised profit in closing inventory', 'Parent', 'Subsidiary', '8,000', 'Increase cost of sales; reduce inventory']], required: ['Eliminate sales/purchases', 'Adjust unrealised profit'] }),
  table('unrealised_profit_inventory_detailed', 'Unrealised profit in inventory table — detailed', 'advanced', 'Group accounts', 'consolidation', 'Calculates PURP in inventory using selling price, margin/markup, and closing inventory held.', { standardFramework: 'IFRS', tableKind: 'unrealised_profit_inventory', columns: ['Goods sold intra-group', 'Profit basis', 'Inventory remaining', 'PURP'], rows: [['50,000', '25% markup on cost', '20,000 at selling price', '4,000']], required: ['Distinguish markup and margin', 'Calculate PURP', 'Adjust inventory and profit'] }),
  table('unrealised_profit_non_current_assets', 'Unrealised profit in non-current assets table', 'advanced', 'Group accounts', 'consolidation', 'Adjusts unrealised profit and excess depreciation on intra-group sale of non-current asset.', { standardFramework: 'IFRS', tableKind: 'unrealised_profit_nca', columns: ['Item', 'Amount'], rows: [['Intra-group profit on asset sale', '30,000'], ['Excess depreciation already charged', '(6,000)'], ['Net adjustment to carrying amount', '24,000']], required: ['Eliminate unrealised profit', 'Adjust excess depreciation'] }),
  table('group_sfp_full_worksheet', 'Group statement of financial position full worksheet', 'advanced', 'Group accounts', 'consolidation', 'Full consolidation worksheet for parent, subsidiary, adjustments, NCI, and group totals.', { standardFramework: 'IFRS', tableKind: 'group_sfp_full_worksheet', columns: ['Line item', 'Parent', 'Subsidiary', 'Adjustments', 'NCI', 'Group'], rows: [['PPE', '300,000', '120,000', '20,000 FV adj', '', '440,000'], ['Investment in subsidiary', '180,000', '', '(180,000)', '', '0'], ['Goodwill', '', '', '30,000', '', '30,000'], ['NCI', '', '', '', '37,000', '37,000']], required: ['Eliminate investment', 'Recognise goodwill', 'Calculate group totals'] }),
  table('group_profit_or_loss_full_worksheet', 'Group statement of profit or loss full worksheet', 'advanced', 'Group accounts', 'consolidation', 'Full group profit or loss worksheet with eliminations and NCI share.', { standardFramework: 'IFRS', tableKind: 'group_profit_or_loss_worksheet', columns: ['Line item', 'Parent', 'Subsidiary', 'Adjustments', 'Group'], rows: [['Revenue', '500,000', '200,000', '(50,000) intra-group sales', '650,000'], ['Cost of sales', '(300,000)', '(120,000)', '50,000 - 4,000 PURP', '(374,000)'], ['Profit after tax', '120,000', '40,000', '(4,000)', '156,000']], required: ['Eliminate intragroup sales', 'Adjust PURP', 'Calculate group profit'] }),
  table('group_statement_changes_equity', 'Group statement of changes in equity worksheet', 'advanced', 'Group accounts', 'consolidation', 'Group equity movement for parent shareholders and NCI.', { standardFramework: 'IFRS', tableKind: 'group_statement_changes_equity', columns: ['Item', 'Parent equity', 'NCI', 'Total equity'], rows: [['Opening balance', '200,000', '30,000', '230,000'], ['Group profit', '120,000', '8,000', '128,000'], ['Dividends', '(20,000)', '(3,000)', '(23,000)'], ['Closing balance', '300,000', '35,000', '335,000']], required: ['Allocate profit', 'Update NCI', 'Prepare group equity movement'] }),
  table('group_cash_flow_worksheet', 'Group cash flow statement worksheet', 'advanced', 'Group accounts', 'consolidation', 'Group cash flow working including subsidiary acquisition/disposal cash effects.', { standardFramework: 'IFRS', tableKind: 'group_cash_flow_worksheet', columns: ['Cash flow item', 'Amount', 'Classification'], rows: [['Cash paid to acquire subsidiary', '(180,000)', 'Investing'], ['Cash acquired with subsidiary', '20,000', 'Investing offset'], ['NCI dividend paid', '(3,000)', 'Financing'], ['Group operating cash flow', '150,000', 'Operating']], required: ['Classify group cash flows', 'Calculate net acquisition cash flow'] }),
  table('step_acquisition_table', 'Step acquisition table', 'advanced', 'Group accounts', 'consolidation', 'Accounting for acquisition achieved in stages and remeasurement of previous interest.', { standardFramework: 'IFRS', tableKind: 'step_acquisition', columns: ['Item', 'Amount'], rows: [['Fair value of previous 30% interest', '70,000'], ['Carrying amount of previous interest', '(55,000)'], ['Remeasurement gain', '15,000'], ['Additional consideration for control', '120,000']], required: ['Remeasure previous interest', 'Include fair value in goodwill'] }),
  table('subsidiary_disposal_table', 'Disposal of subsidiary table', 'advanced', 'Group accounts', 'consolidation', 'Calculates group gain/loss on disposal of subsidiary.', { standardFramework: 'IFRS', tableKind: 'subsidiary_disposal', columns: ['Item', 'Amount'], rows: [['Proceeds received', '220,000'], ['Less net assets disposed', '(160,000)'], ['Less goodwill disposed', '(30,000)'], ['Add NCI derecognised', '35,000'], ['Gain on disposal', '65,000']], required: ['Calculate group disposal gain/loss', 'Derecognise NCI and goodwill'] }),
  table('partial_disposal_table', 'Partial disposal table', 'advanced', 'Group accounts', 'consolidation', 'Partial disposal with or without loss of control.', { standardFramework: 'IFRS', tableKind: 'partial_disposal', columns: ['Scenario', 'Control retained?', 'Accounting treatment'], rows: [['Sell 10%, ownership falls from 80% to 70%', 'Yes', 'Equity transaction with NCI'], ['Sell 60%, ownership falls from 80% to 20%', 'No', 'Recognise gain/loss and remeasure retained interest']], required: ['Assess control', 'State accounting treatment'] }),
  table('associate_impairment_table', 'Associate impairment table', 'advanced', 'Group accounts', 'consolidation', 'Tests investment in associate for impairment after equity method adjustments.', { standardFramework: 'IFRS', tableKind: 'associate_impairment', columns: ['Item', 'Amount'], rows: [['Carrying amount before impairment', '80,000'], ['Recoverable amount', '65,000'], ['Impairment loss', '15,000']], required: ['Calculate impairment', 'Adjust carrying amount of associate'] }),
  table('joint_arrangement_classification', 'Joint arrangement classification table', 'advanced', 'Group accounts', 'consolidation', 'Classifies joint arrangements as joint operation or joint venture.', { standardFramework: 'IFRS', tableKind: 'joint_arrangement_classification', columns: ['Factor', 'Evidence', 'Conclusion'], rows: [['Legal form', 'Separate vehicle exists', 'May indicate joint venture'], ['Rights to assets/obligations', 'Parties have direct rights to assets', 'Joint operation'], ['Conclusion', 'Substance over form', 'Joint operation']], required: ['Assess rights and obligations', 'Classify arrangement'] }),
  table('joint_operation_accounting', 'Joint operation accounting table', 'advanced', 'Group accounts', 'consolidation', 'Recognises share of joint operation assets, liabilities, income, and expenses.', { standardFramework: 'IFRS', tableKind: 'joint_operation_accounting', columns: ['Item', 'Total operation', 'Entity share', 'Recognised amount'], rows: [['Assets', '100,000', '40%', '40,000'], ['Liabilities', '30,000', '40%', '12,000'], ['Revenue', '80,000', '40%', '32,000'], ['Expenses', '50,000', '40%', '20,000']], required: ['Calculate share', 'Recognise assets/liabilities/income/expenses'] }),
  table('consolidation_adjustment_journals', 'Consolidation adjustment journal table', 'advanced', 'Group accounts', 'consolidation', 'Journal-style list of consolidation adjustments.', { standardFramework: 'IFRS', tableKind: 'consolidation_adjustment_journals', columns: ['Adjustment', 'Debit', 'Credit', 'Amount'], rows: [['Eliminate investment', 'Share capital / pre-acquisition reserves / goodwill', 'Investment in subsidiary', '180,000'], ['Eliminate intragroup sale', 'Revenue', 'Cost of sales', '50,000'], ['Adjust PURP', 'Cost of sales', 'Inventory', '4,000']], required: ['Prepare consolidation journals', 'Explain each adjustment'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
