import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const coreLedgerAccountingTables: AccountingTableTemplate[] = [
  table('single_column_cash_book', 'Single-column cash book', 'beginner', 'Cash book', 'case_study', 'Cash-only receipts and payments book for early bookkeeping practice.', { tableKind: 'single_column_cash_book', columns: ['Date', 'Details', 'Receipt', 'Payment', 'Balance'], rows: [['Jan 1', 'Capital introduced', '10,000', '', '10,000'], ['Jan 3', 'Rent paid', '', '1,500', '8,500'], ['Jan 5', 'Cash sales', '2,000', '', '10,500']], required: ['Record receipts and payments', 'Calculate the running balance'] }),
  table('two_column_cash_book', 'Two-column cash book', 'beginner', 'Cash book', 'case_study', 'Cash and bank columns without discounts.', { tableKind: 'two_column_cash_book', columns: ['Date', 'Details', 'Cash Dr', 'Bank Dr', 'Date', 'Details', 'Cash Cr', 'Bank Cr'], rows: [['Jan 1', 'Capital', '5,000', '15,000', 'Jan 2', 'Purchases', '2,000', ''], ['Jan 4', 'Cash sales', '3,500', '', 'Jan 6', 'Rent', '', '2,500']], required: ['Record cash and bank transactions', 'Balance both columns'] }),
  table('double_column_cash_book', 'Double-column cash book', 'beginner', 'Cash book', 'case_study', 'Cash book with cash and bank columns, including contra entries.', { tableKind: 'double_column_cash_book', columns: ['Date', 'Details', 'Cash Dr', 'Bank Dr', 'Date', 'Details', 'Cash Cr', 'Bank Cr'], rows: [['Jan 1', 'Balance b/d', '1,000', '8,000', 'Jan 3', 'Purchases', '500', ''], ['Jan 5', 'Cash sales', '2,000', '', 'Jan 6', 'Bank C', '1,500', ''], ['Jan 6', 'Cash C', '', '1,500', 'Jan 8', 'Rent', '', '1,000']], required: ['Identify contra entries', 'Balance cash and bank columns'] }),
  table('transaction_analysis_grid', 'Transaction analysis grid', 'beginner', 'Double entry', 'case_study', 'Analyses each transaction before journalising: accounts, class, effect, debit, and credit.', { tableKind: 'transaction_analysis_grid', columns: ['Transaction', 'Account affected', 'Class', 'Increase/decrease', 'Debit/Credit'], rows: [['Owner invests cash', 'Cash', 'Asset', 'Increase', 'Debit'], ['Owner invests cash', 'Capital', 'Equity', 'Increase', 'Credit'], ['Paid rent', 'Rent expense', 'Expense', 'Increase', 'Debit'], ['Paid rent', 'Cash', 'Asset', 'Decrease', 'Credit']], required: ['Identify accounts', 'Classify accounts', 'Apply debit and credit rules'] }),
  table('normal_balance_drill_table', 'Normal balance drill table', 'beginner', 'Double entry', 'concept', 'Drill table for account classes, normal balance, and increase/decrease treatment.', { concept: 'Normal balance drill', tableKind: 'normal_balance_drill', columns: ['Account', 'Class', 'Normal balance', 'Increase side', 'Decrease side'], rows: [['Cash', 'Asset', 'Debit', 'Debit', 'Credit'], ['Loan payable', 'Liability', 'Credit', 'Credit', 'Debit'], ['Sales', 'Income', 'Credit', 'Credit', 'Debit'], ['Wages', 'Expense', 'Debit', 'Debit', 'Credit']] }),
  table('capital_account', 'Capital account', 'beginner', 'Equity', 'ledger', 'Sole trader capital account showing opening capital, additional capital, profit, drawings, and closing capital.', { currency: 'ZMW', tableKind: 'capital_account', accountName: 'Capital Account', debitEntries: [{ details: 'Drawings', amount: 3000 }, { details: 'Balance c/d', amount: 27000 }], creditEntries: [{ details: 'Balance b/d', amount: 20000 }, { details: 'Additional capital', amount: 5000 }, { details: 'Profit for the year', amount: 5000 }] }),
  table('drawings_account', 'Drawings account', 'beginner', 'Equity', 'ledger', 'Records cash or goods withdrawn by the owner for personal use.', { currency: 'ZMW', tableKind: 'drawings_account', accountName: 'Drawings Account', debitEntries: [{ details: 'Cash drawings', amount: 2000 }, { details: 'Goods withdrawn', amount: 1000 }], creditEntries: [{ details: 'Capital account', amount: 3000 }] }),
  table('expenses_ledger_table', 'Expenses ledger table', 'beginner', 'Ledger posting', 'ledger', 'Expense account format for rent, wages, utilities, and other period expenses.', { currency: 'ZMW', tableKind: 'expenses_ledger', accountName: 'Rent Expense Account', debitEntries: [{ details: 'Bank', amount: 12000 }, { details: 'Accrued rent c/d', amount: 2000 }], creditEntries: [{ details: 'Income statement', amount: 14000 }] }),
  table('income_ledger_table', 'Income ledger table', 'beginner', 'Ledger posting', 'ledger', 'Income account format for sales, commission, rent received, and other income.', { currency: 'ZMW', tableKind: 'income_ledger', accountName: 'Sales Account', debitEntries: [{ details: 'Income statement', amount: 50000 }], creditEntries: [{ details: 'Cash/Receivables', amount: 50000 }] }),
  table('trial_balance_extraction_worksheet', 'Trial balance extraction worksheet', 'beginner', 'Trial balance', 'case_study', 'Worksheet for moving ledger balances into debit or credit trial balance columns.', { tableKind: 'trial_balance_extraction_worksheet', columns: ['Ledger account', 'Balance amount', 'Balance side', 'Trial balance debit', 'Trial balance credit'], rows: [['Cash', '8,000', 'Debit', '8,000', ''], ['Capital', '10,000', 'Credit', '', '10,000'], ['Purchases', '2,000', 'Debit', '2,000', '']], required: ['Determine balance side', 'Place each balance in the correct trial balance column'] }),
  table('control_account_reconciliation_statement', 'Control account reconciliation statement', 'intermediate', 'Control accounts', 'case_study', 'Reconciles ledger control account balance to the list of individual customer or supplier balances.', { tableKind: 'control_account_reconciliation_statement', columns: ['Item', 'Amount'], rows: [['Balance per control account', '15,000'], ['Add: sales invoice omitted from control account', '1,200'], ['Less: receipt omitted from customer account', '(800)'], ['Corrected balance / schedule total', '15,400']], required: ['Correct the control account', 'Correct the subsidiary ledger', 'Agree both balances'] }),
  table('aged_receivables_analysis', 'Aged receivables analysis', 'intermediate', 'Receivables', 'case_study', 'Classifies receivables by age bands for collection risk and allowance decisions.', { tableKind: 'aged_receivables_analysis', columns: ['Customer', 'Current', '31-60 days', '61-90 days', 'Over 90 days', 'Total'], rows: [['Banda Stores', '1,000', '800', '400', '', '2,200'], ['Copper Mart', '2,500', '', '600', '900', '4,000']], required: ['Age customer balances', 'Identify high-risk receivables', 'Recommend allowance action'] }),
  table('aged_payables_analysis', 'Aged payables analysis', 'intermediate', 'Payables', 'case_study', 'Classifies supplier balances by age bands for payment planning.', { tableKind: 'aged_payables_analysis', columns: ['Supplier', 'Current', '31-60 days', '61-90 days', 'Over 90 days', 'Total'], rows: [['Zed Supplies', '1,500', '700', '', '', '2,200'], ['Ndola Wholesalers', '2,000', '1,000', '500', '', '3,500']], required: ['Age supplier balances', 'Prioritise payments', 'Explain liquidity impact'] }),
  table('allowance_for_receivables_movement', 'Allowance for receivables movement table', 'intermediate', 'Receivables', 'case_study', 'Shows opening allowance, required closing allowance, increase/decrease, and income statement effect.', { tableKind: 'allowance_movement', columns: ['Item', 'Amount'], rows: [['Opening allowance', '800'], ['Required closing allowance', '1,200'], ['Increase in allowance / expense', '400'], ['Net receivables presentation', 'Receivables less allowance']], required: ['Calculate movement', 'State income statement charge', 'State statement of financial position presentation'] }),
  table('bad_debts_recovered_account', 'Bad debts recovered account', 'intermediate', 'Receivables', 'ledger', 'Records recovery of a debt previously written off.', { currency: 'ZMW', tableKind: 'bad_debts_recovered_account', accountName: 'Bad Debts Recovered Account', debitEntries: [{ details: 'Income statement', amount: 600 }], creditEntries: [{ details: 'Bank', amount: 600 }] }),
  table('weighted_average_stock_card', 'Inventory weighted average stock card', 'intermediate', 'Inventory', 'inventory', 'Perpetual weighted average inventory card for receipts, issues, and closing inventory.', { tableKind: 'weighted_average_stock_card', method: 'weighted_average', transactions: [{ type: 'purchase', units: 100, unitCost: 20 }, { type: 'purchase', units: 50, unitCost: 24 }, { type: 'sale', units: 120 }], columns: ['Date', 'Receipts', 'Issues', 'Balance qty', 'Average cost', 'Balance value'], rows: [['Jan 1', '100 @ K20', '', '100', 'K20.00', 'K2,000'], ['Jan 5', '50 @ K24', '', '150', 'K21.33', 'K3,200'], ['Jan 10', '', '120 @ K21.33', '30', 'K21.33', 'K640']], required: ['Calculate weighted average cost', 'Calculate issue value', 'Calculate closing inventory'] }),
  table('inventory_nrv_comparison', 'Inventory NRV comparison table', 'intermediate', 'Inventory', 'case_study', 'Compares cost and net realisable value item-by-item and applies lower of cost and NRV.', { tableKind: 'inventory_nrv_comparison', columns: ['Item', 'Cost', 'NRV', 'Value to report'], rows: [['Product A', '5,000', '4,400', '4,400'], ['Product B', '3,000', '3,800', '3,000']], required: ['Compare cost and NRV', 'Choose lower value', 'Calculate write-down'] }),
  table('payroll_register', 'Payroll register', 'intermediate', 'Payroll', 'case_study', 'Gross pay, deductions, employer contributions, and net pay schedule.', { tableKind: 'payroll_register', columns: ['Employee', 'Basic pay', 'Allowances', 'Gross pay', 'PAYE', 'NAPSA', 'NHIMA', 'Net pay'], rows: [['A. Banda', '5,000', '500', '5,500', '600', '275', '55', '4,570'], ['C. Muloongo', '7,000', '700', '7,700', '1,000', '385', '77', '6,238']], required: ['Calculate gross pay', 'Calculate deductions', 'Calculate net pay'] }),
  table('wages_control_account', 'Wages control account', 'intermediate', 'Payroll', 'ledger', 'Control account for gross wages, deductions, net pay, and employer obligations.', { currency: 'ZMW', tableKind: 'wages_control_account', accountName: 'Wages Control Account', debitEntries: [{ details: 'Wages expense', amount: 13200 }], creditEntries: [{ details: 'Bank net pay', amount: 10808 }, { details: 'PAYE payable', amount: 1600 }, { details: 'NAPSA payable', amount: 660 }, { details: 'NHIMA payable', amount: 132 }] }),
  table('correction_of_errors_classification', 'Correction of errors classification table', 'intermediate', 'Error correction', 'case_study', 'Classifies errors by type and whether the trial balance is affected.', { tableKind: 'error_classification', columns: ['Error', 'Type', 'Affects trial balance?', 'Correction needed'], rows: [['Omitted purchase invoice', 'Complete omission', 'No', 'Record full journal'], ['Sales account undercast', 'Casting error', 'Yes', 'Use suspense if opened'], ['Rent posted to repairs', 'Error of principle/classification', 'No', 'Reclassify expense']], required: ['Classify each error', 'State trial balance effect', 'Prepare correction'] }),
  table('statement_of_corrected_net_profit', 'Statement of corrected net profit', 'intermediate', 'Error correction', 'case_study', 'Adjusts draft profit for errors and omissions.', { tableKind: 'corrected_net_profit', columns: ['Item', 'Effect on profit', 'Amount'], rows: [['Draft net profit', '', '25,000'], ['Add: sales undercast', 'Increase', '1,200'], ['Less: rent omitted', 'Decrease', '(2,000)'], ['Corrected net profit', '', '24,200']], required: ['Identify profit effect', 'Calculate corrected profit'] }),
  table('receipts_and_payments_account', 'Receipts and payments account', 'intermediate', 'Non-profit accounts', 'case_study', 'Cash summary for non-profit accounting before preparing income and expenditure account.', { tableKind: 'receipts_and_payments_account', columns: ['Receipts', 'Amount', 'Payments', 'Amount'], rows: [['Balance b/d', '5,000', 'Rent', '4,000'], ['Subscriptions received', '30,500', 'Salaries', '10,000'], ['Donations', '5,000', 'Equipment', '8,000']], required: ['Summarise cash receipts and payments', 'Use adjustments to prepare income and expenditure account'] }),
  table('trading_account', 'Trading account', 'intermediate', 'Final accounts', 'financial_statement', 'Calculates gross profit using sales, returns, opening inventory, purchases, carriage, and closing inventory.', { currency: 'ZMW', standardFramework: 'Trading account format', statementType: 'trading_account', businessName: 'Muloongo Traders', period: 'Year ended 31 December 2026', sections: [{ title: 'Sales', items: [{ name: 'Sales', amount: 90000 }, { name: 'Less sales returns', amount: -3000 }] }, { title: 'Cost of sales', items: [{ name: 'Opening inventory', amount: 10000 }, { name: 'Purchases', amount: 45000 }, { name: 'Carriage inwards', amount: 2000 }, { name: 'Closing inventory', amount: -12000 }] }] }),
  table('sole_trader_capital_movement', 'Sole trader capital movement table', 'intermediate', 'Final accounts', 'case_study', 'Reconciles opening capital, additional capital, profit, drawings, and closing capital.', { tableKind: 'capital_movement', columns: ['Item', 'Amount'], rows: [['Opening capital', '20,000'], ['Add: additional capital', '5,000'], ['Add: profit', '8,000'], ['Less: drawings', '(3,000)'], ['Closing capital', '30,000']], required: ['Calculate closing capital', 'Explain effect of drawings and profit'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
