import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const errorSuspenseAccountingTables: AccountingTableTemplate[] = [
  table('trial_balance_difference_analysis', 'Trial balance difference analysis table', 'intermediate', 'Error correction and suspense', 'case_study', 'Analyses a trial balance difference before opening or clearing a suspense account.', { tableKind: 'trial_balance_difference_analysis', columns: ['Check', 'Purpose', 'Example', 'Result'], rows: [['Difference amount', 'Identify size of imbalance', 'Debit total K42,500; Credit total K41,800', 'Difference K700'], ['Half difference', 'May indicate posting to wrong side', 'K700 / 2', 'K350 clue'], ['Double difference', 'May indicate omission from one side', 'K700 x 2', 'K1,400 clue'], ['Transposition check', 'Difference divisible by 9', 'K702 divisible by 9?', 'Possible transposition']], required: ['Calculate the difference', 'Use diagnostic checks', 'Suggest likely error type'] }),
  table('suspense_account_opening_entry', 'Suspense account opening entry table', 'intermediate', 'Error correction and suspense', 'journal_entry', 'Opening suspense account entry when the trial balance does not agree.', { currency: 'ZMW', tableKind: 'suspense_opening_entry', question: 'Debit total exceeds credit total by K700. Open the suspense account to balance the trial balance.', rows: [{ account: 'Suspense Account', debit: 0, credit: 700 }], columns: ['Account', 'Debit', 'Credit', 'Narration'], required: ['Determine suspense side', 'Record opening suspense entry'] }, { rows: [{ account: 'Suspense Account', debit: 0, credit: 700 }] }),
  table('suspense_account_full_working', 'Suspense account full working table', 'intermediate', 'Error correction and suspense', 'ledger', 'Full suspense account showing opening difference, correction entries, and closing balance.', { currency: 'ZMW', tableKind: 'suspense_account_full_working', accountName: 'Suspense Account', debitEntries: [{ details: 'Correction: sales account undercast', amount: 700 }, { details: 'Correction: purchase posted to wrong side', amount: 400 }], creditEntries: [{ details: 'Difference on trial balance', amount: 700 }, { details: 'Correction: discount received omitted', amount: 400 }], required: ['Post corrections', 'Clear the suspense account', 'Identify unresolved balance if any'] }),
  table('suspense_error_by_error_worksheet', 'Suspense error-by-error correction worksheet', 'intermediate', 'Error correction and suspense', 'case_study', 'Shows each error, trial balance effect, suspense effect, and correction journal.', { tableKind: 'suspense_error_by_error_worksheet', columns: ['Error', 'Affects trial balance?', 'Suspense debit', 'Suspense credit', 'Correction journal'], rows: [['Sales account undercast by K700', 'Yes', 'Sales K700', 'Suspense K700', 'Dr Suspense K700; Cr Sales K700'], ['Rent paid posted only to bank', 'Yes', 'Rent K1,000', 'Suspense K1,000', 'Dr Rent K1,000; Cr Suspense K1,000'], ['Purchase invoice completely omitted', 'No', '', '', 'Dr Purchases; Cr Payables']], required: ['Decide if suspense is affected', 'Prepare correction journal', 'Update suspense account'] }),
  table('errors_not_affecting_trial_balance', 'Errors not affecting trial balance table', 'intermediate', 'Error correction and suspense', 'case_study', 'Classifies complete omission, original entry, commission, principle, and compensating errors.', { tableKind: 'errors_not_affecting_trial_balance', columns: ['Error type', 'Example', 'Trial balance effect', 'Correction approach'], rows: [['Complete omission', 'Purchase invoice not recorded anywhere', 'No effect', 'Record full double entry'], ['Original entry', 'Invoice K900 recorded as K90 in both accounts', 'No effect', 'Correct difference in both accounts'], ['Commission', 'Posted to wrong customer', 'No effect', 'Transfer between personal accounts'], ['Principle', 'Capital expenditure posted to repairs', 'No effect', 'Reclassify asset/expense'], ['Compensating', 'Two errors cancel each other', 'No effect', 'Correct each error separately']], required: ['Classify error type', 'Explain why trial balance still agrees'] }),
  table('errors_affecting_trial_balance', 'Errors affecting trial balance table', 'intermediate', 'Error correction and suspense', 'case_study', 'Classifies one-sided errors, casting errors, wrong-side postings, and unequal entries.', { tableKind: 'errors_affecting_trial_balance', columns: ['Error type', 'Example', 'Trial balance effect', 'Suspense needed?', 'Correction'], rows: [['One-sided omission', 'Cash received posted to cash only', 'Debit excess', 'Yes', 'Credit missing account / use suspense'], ['Casting error', 'Sales day book undercast', 'Credit short', 'Yes', 'Credit sales / debit suspense'], ['Wrong-side posting', 'Rent debit posted as credit', 'Double effect', 'Yes', 'Correct double amount'], ['Unequal entry', 'Debit K500; credit K50', 'Difference K450', 'Yes', 'Correct short side']], required: ['Identify trial balance effect', 'Use suspense correctly'] }),
  table('wrong_side_posting_correction', 'Wrong-side posting correction table', 'intermediate', 'Error correction and suspense', 'case_study', 'Shows why wrong-side postings are corrected with double the amount.', { tableKind: 'wrong_side_posting_correction', columns: ['Item', 'Amount'], rows: [['Rent should have been debited', 'K1,000'], ['Rent was wrongly credited', 'K1,000'], ['Correction needed', 'Debit Rent K2,000'], ['Suspense/other side', 'Credit Suspense K2,000']], required: ['Explain double correction', 'Prepare journal entry'] }),
  table('transposition_error_detection', 'Transposition error detection table', 'intermediate', 'Error correction and suspense', 'case_study', 'Uses divisibility by 9 to identify possible transposition errors.', { tableKind: 'transposition_error_detection', columns: ['Correct figure', 'Recorded figure', 'Difference', 'Divisible by 9?', 'Conclusion'], rows: [['K1,260', 'K1,620', 'K360', 'Yes', 'Likely transposition'], ['K4,850', 'K4,580', 'K270', 'Yes', 'Likely transposition']], required: ['Calculate difference', 'Test divisibility by 9', 'Identify possible transposition'] }),
  table('casting_error_correction_table', 'Casting error correction table', 'intermediate', 'Error correction and suspense', 'case_study', 'Corrects undercasting and overcasting of books of original entry and ledger accounts.', { tableKind: 'casting_error_correction', columns: ['Book/account', 'Error', 'Effect', 'Correction'], rows: [['Sales day book', 'Undercast by K900', 'Sales understated', 'Cr Sales K900; Dr Suspense K900'], ['Purchases account', 'Overcast by K500', 'Purchases overstated', 'Cr Purchases K500; Dr Suspense K500']], required: ['Identify overcast/undercast effect', 'Prepare correction'] }),
  table('error_of_principle_correction', 'Error of principle correction table', 'intermediate', 'Error correction and suspense', 'journal_entry', 'Corrects capital/revenue classification errors.', { currency: 'ZMW', tableKind: 'error_of_principle_correction', question: 'Repairs expense of K5,000 was actually machinery purchased and should have been capitalised.', rows: [{ account: 'Machinery', debit: 5000, credit: 0 }, { account: 'Repairs Expense', debit: 0, credit: 5000 }], columns: ['Account', 'Debit', 'Credit', 'Narration'], required: ['Identify classification error', 'Prepare reclassification journal'] }, { rows: [{ account: 'Machinery', debit: 5000, credit: 0 }, { account: 'Repairs Expense', debit: 0, credit: 5000 }] }),
  table('error_of_commission_correction', 'Error of commission correction table', 'intermediate', 'Error correction and suspense', 'journal_entry', 'Corrects posting to the wrong personal account within the same class.', { currency: 'ZMW', tableKind: 'error_of_commission_correction', question: 'A receipt from Banda Stores K800 was posted to Copper Mart account.', rows: [{ account: 'Copper Mart Receivable', debit: 800, credit: 0 }, { account: 'Banda Stores Receivable', debit: 0, credit: 800 }], columns: ['Account', 'Debit', 'Credit', 'Narration'], required: ['Identify wrong personal account', 'Transfer balance to correct account'] }),
  table('compensating_errors_table', 'Compensating errors table', 'intermediate', 'Error correction and suspense', 'case_study', 'Shows errors that cancel each other and therefore do not affect the trial balance.', { tableKind: 'compensating_errors', columns: ['Error 1', 'Effect', 'Error 2', 'Effect', 'Net TB effect'], rows: [['Purchases overcast K600', 'Debit overstated', 'Wages undercast K600', 'Debit understated', 'No difference'], ['Sales overcast K400', 'Credit overstated', 'Discount received undercast K400', 'Credit understated', 'No difference']], required: ['Identify compensating relationship', 'Correct each error separately'] }),
  table('corrected_trial_balance_after_suspense', 'Corrected trial balance after suspense table', 'intermediate', 'Error correction and suspense', 'trial_balance', 'Trial balance after errors are corrected and suspense is cleared.', { currency: 'ZMW', tableKind: 'corrected_trial_balance_after_suspense', title: 'Corrected Trial Balance', accounts: [{ name: 'Cash', debit: 8500, credit: 0 }, { name: 'Purchases', debit: 12000, credit: 0 }, { name: 'Rent', debit: 3000, credit: 0 }, { name: 'Sales', debit: 0, credit: 18500 }, { name: 'Capital', debit: 0, credit: 5000 }], required: ['Apply corrections', 'Confirm trial balance agreement'] }),
  table('suspense_clearance_checklist', 'Suspense clearance checklist', 'intermediate', 'Error correction and suspense', 'case_study', 'Checklist to confirm every suspense-causing error has been corrected.', { tableKind: 'suspense_clearance_checklist', columns: ['Check', 'Yes/No', 'Evidence'], rows: [['Opening suspense balance recorded?', 'Yes', 'Trial balance difference'], ['All one-sided errors corrected?', 'No', 'Review ledger postings'], ['Wrong-side postings doubled?', 'Yes', 'Correction journal'], ['Suspense account balance now zero?', 'Pending', 'Ledger balance']], required: ['Verify corrections', 'Confirm suspense balance is zero'] }),
  table('profit_effect_of_errors_table', 'Profit effect of errors table', 'intermediate', 'Error correction and suspense', 'case_study', 'Analyses whether each error overstates or understates profit.', { tableKind: 'profit_effect_of_errors', columns: ['Error', 'Profit effect', 'Amount', 'Correction to profit'], rows: [['Closing inventory overstated', 'Profit overstated', 'K2,000', 'Subtract K2,000'], ['Expense omitted', 'Profit overstated', 'K1,500', 'Subtract K1,500'], ['Sales undercast', 'Profit understated', 'K900', 'Add K900']], required: ['Identify profit effect', 'Calculate corrected profit'] }),
  table('statement_of_revised_profit_after_errors', 'Statement of revised profit after errors', 'intermediate', 'Error correction and suspense', 'case_study', 'Formal statement correcting draft profit for discovered errors.', { tableKind: 'revised_profit_after_errors', columns: ['Item', 'Amount'], rows: [['Draft profit', '25,000'], ['Add: sales undercast', '900'], ['Less: expense omitted', '(1,500)'], ['Less: inventory overstated', '(2,000)'], ['Revised profit', '22,400']], required: ['Adjust draft profit', 'Calculate revised profit'] }),
  table('statement_of_corrected_financial_position_extract', 'Corrected statement of financial position extract after errors', 'intermediate', 'Error correction and suspense', 'financial_statement', 'Updates asset, liability, and capital balances after error correction.', { currency: 'ZMW', standardFramework: 'Error correction extract', tableKind: 'corrected_sfp_extract', statementType: 'statement_of_financial_position_extract', businessName: 'Error Correction Case', period: 'After corrections', sections: [{ title: 'Assets', items: [{ name: 'Inventory after correction', amount: 10000 }, { name: 'Receivables after correction', amount: 8000 }] }, { title: 'Equity and liabilities', items: [{ name: 'Capital after revised profit', amount: 22400 }, { name: 'Payables after correction', amount: 5600 }] }], required: ['Update balances after correction', 'Show corrected SFP extract'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
