import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const ifrsReportingAccountingTables: AccountingTableTemplate[] = [
  table('rou_asset_depreciation_schedule', 'Right-of-use asset depreciation schedule', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IFRS 16 right-of-use asset cost, depreciation, impairment, and carrying amount.', { standardFramework: 'IFRS', evidenceStandard: 'Apply IFRS 16 ROU asset measurement and depreciation.', tableKind: 'rou_asset_depreciation_schedule', columns: ['Year', 'Opening carrying amount', 'Additions/modifications', 'Depreciation', 'Impairment', 'Closing carrying amount'], rows: [['1', '100,000', '', '(20,000)', '', '80,000'], ['2', '80,000', '10,000', '(22,500)', '', '67,500']], required: ['Calculate ROU depreciation', 'Explain carrying amount presentation'] }),
  table('lease_modification_table', 'Lease modification table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Assesses lease modification effect on liability, ROU asset, and gain/loss.', { standardFramework: 'IFRS', tableKind: 'lease_modification', columns: ['Change', 'Accounting assessment', 'Liability effect', 'ROU asset effect', 'P/L effect'], rows: [['Lease term extended', 'Remeasure lease liability', 'Increase liability', 'Adjust ROU asset', 'None immediately'], ['Scope reduced', 'Partial termination', 'Reduce liability', 'Reduce ROU asset', 'Recognise gain/loss']], required: ['Classify modification', 'State accounting treatment'] }),
  table('sale_and_leaseback_table', 'Sale and leaseback table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Analyses sale and leaseback transaction under IFRS 15 and IFRS 16.', { standardFramework: 'IFRS', tableKind: 'sale_and_leaseback', columns: ['Step', 'Assessment', 'Accounting treatment'], rows: [['Sale assessment', 'Does transfer qualify as sale under IFRS 15?', 'If yes, recognise partial gain'], ['ROU retained', 'Seller-lessee retains right of use', 'Measure ROU asset as proportion retained'], ['Lease liability', 'Present value of payments', 'Recognise lease liability']], required: ['Assess sale', 'Calculate gain portion', 'Measure ROU asset and lease liability'] }),
  table('ifrs16_exemption_table', 'IFRS 16 exemption table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Short-term and low-value lease exemption decision table.', { standardFramework: 'IFRS', tableKind: 'ifrs16_exemption', columns: ['Lease', 'Term', 'Low-value?', 'Exemption allowed?', 'Treatment'], rows: [['Laptop lease', '24 months', 'Yes', 'Possible low-value', 'Expense straight-line if elected'], ['Warehouse lease', '10 years', 'No', 'No', 'Recognise ROU asset and liability']], required: ['Assess exemption', 'Explain treatment'] }),
  table('revaluation_surplus_movement', 'Revaluation surplus movement table', 'advanced', 'IFRS reporting', 'financial_statement', 'IAS 16 revaluation surplus movement with gains, transfers, depreciation, and disposals.', { currency: 'ZMW', standardFramework: 'IFRS', tableKind: 'revaluation_surplus_movement', columns: ['Item', 'Amount'], rows: [['Opening revaluation surplus', '30,000'], ['Revaluation gain', '20,000'], ['Transfer due to excess depreciation', '(2,000)'], ['Disposal transfer', '(5,000)'], ['Closing revaluation surplus', '43,000']], required: ['Calculate revaluation surplus movement', 'Explain OCI and reserve transfer'] }),
  table('ppe_disposal_revaluation_combined', 'PPE disposal and revaluation combined table', 'advanced', 'IFRS reporting', 'financial_statement', 'Combined PPE working for cost model/revaluation model, disposal, and gain/loss.', { standardFramework: 'IFRS', tableKind: 'ppe_disposal_revaluation_combined', columns: ['Asset', 'Carrying amount before event', 'Revaluation/disposal proceeds', 'Accounting effect', 'Closing carrying amount'], rows: [['Building', '200,000', 'Fair value 240,000', 'Revaluation gain 40,000', '240,000'], ['Machine', '50,000', 'Proceeds 42,000', 'Loss 8,000', '0']], required: ['Calculate revaluation gain/loss', 'Calculate disposal gain/loss'] }),
  table('intangible_assets_movement', 'Intangible assets movement schedule', 'advanced', 'IFRS reporting', 'financial_statement', 'IAS 38 intangible cost, amortisation, impairment, and carrying amount.', { currency: 'ZMW', standardFramework: 'IFRS', tableKind: 'intangible_assets_movement', columns: ['Item', 'Cost', 'Accumulated amortisation/impairment', 'Carrying amount'], rows: [['Opening balance', '80,000', '(20,000)', '60,000'], ['Development costs capitalised', '30,000', '', '30,000'], ['Amortisation', '', '(10,000)', '(10,000)'], ['Closing balance', '110,000', '(30,000)', '80,000']], required: ['Prepare intangible asset note', 'Explain recognition criteria'] }),
  table('research_vs_development_expenditure', 'Research vs development expenditure table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 38 classification of research expenditure, development expenditure, capitalisation, and expensing.', { standardFramework: 'IFRS', tableKind: 'research_vs_development', columns: ['Project cost', 'Phase', 'Capitalisation criteria met?', 'Treatment'], rows: [['Feasibility study', 'Research', 'No', 'Expense'], ['Prototype after technical feasibility', 'Development', 'Yes', 'Capitalise'], ['Marketing launch', 'Commercial', 'No', 'Expense']], required: ['Classify phase', 'Apply capitalisation criteria'] }),
  table('investment_property_fair_value', 'Investment property fair value movement table', 'advanced', 'IFRS reporting', 'financial_statement', 'IAS 40 investment property fair value gains/losses and carrying amount.', { standardFramework: 'IFRS', tableKind: 'investment_property_fair_value', columns: ['Item', 'Amount'], rows: [['Opening fair value', '300,000'], ['Additions', '50,000'], ['Fair value gain', '25,000'], ['Closing fair value', '375,000']], required: ['Calculate closing fair value', 'Explain P/L fair value movement'] }),
  table('government_grants_schedule', 'Government grants schedule', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Government grant recognition schedule for asset grants and income grants.', { standardFramework: 'IFRS', tableKind: 'government_grants_schedule', columns: ['Grant type', 'Amount', 'Recognition basis', 'Current year income', 'Deferred income'], rows: [['Asset grant', '50,000', 'Over asset useful life', '10,000', '40,000'], ['Income grant', '20,000', 'Match related costs', '20,000', '0']], required: ['Classify grant', 'Recognise income and deferred income'] }),
  table('borrowing_costs_capitalisation', 'Borrowing costs capitalisation table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 23 borrowing costs eligible for capitalisation.', { standardFramework: 'IFRS', tableKind: 'borrowing_costs_capitalisation', columns: ['Borrowing', 'Rate', 'Qualifying asset expenditure', 'Capitalised cost', 'Expensed cost'], rows: [['Specific loan', '10%', '500,000 for 6 months', '25,000', '0'], ['General borrowing', '8%', '100,000 weighted expenditure', '8,000', '2,000']], required: ['Identify qualifying asset', 'Calculate borrowing cost capitalised'] }),
  table('events_after_reporting_period', 'Events after reporting period matrix', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 10 adjusting vs non-adjusting event decision matrix.', { standardFramework: 'IFRS', tableKind: 'ias10_events_matrix', columns: ['Event', 'Evidence of condition at reporting date?', 'Adjusting?', 'Treatment'], rows: [['Customer bankruptcy after year-end due to old financial difficulty', 'Yes', 'Yes', 'Adjust receivable'], ['Fire after year-end', 'No', 'No', 'Disclose if material']], required: ['Classify event', 'State adjustment/disclosure'] }),
  table('functional_currency_assessment', 'Functional currency assessment table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 21 functional currency factors and conclusion.', { standardFramework: 'IFRS', tableKind: 'functional_currency_assessment', columns: ['Factor', 'Evidence', 'Currency indicated'], rows: [['Sales prices', 'Mainly USD', 'USD'], ['Costs', 'Mainly ZMW', 'ZMW'], ['Financing', 'USD loans', 'USD'], ['Conclusion', 'Primary economic environment', 'USD']], required: ['Assess primary indicators', 'Conclude functional currency'] }),
  table('foreign_operation_translation_reserve', 'Foreign operation translation reserve table', 'advanced', 'IFRS reporting', 'financial_statement', 'Translation reserve movement for foreign subsidiary consolidation.', { standardFramework: 'IFRS', tableKind: 'foreign_operation_translation_reserve', columns: ['Item', 'Amount'], rows: [['Opening translation reserve', '12,000'], ['Exchange difference on net assets', '8,000'], ['Exchange difference on goodwill', '2,000'], ['Closing translation reserve', '22,000']], required: ['Calculate translation reserve movement', 'Explain OCI presentation'] }),
  table('related_party_disclosure', 'Related party disclosure table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 24 relationship, transactions, balances, and disclosure requirements.', { standardFramework: 'IFRS', tableKind: 'related_party_disclosure', columns: ['Related party', 'Relationship', 'Transaction', 'Closing balance', 'Disclosure needed?'], rows: [['Director-owned supplier', 'Key management relationship', 'Purchases K50,000', 'Payable K8,000', 'Yes'], ['Parent company', 'Control relationship', 'Management fees K20,000', 'Receivable K5,000', 'Yes']], required: ['Identify relationship', 'State disclosure requirement'] }),
  table('segment_reporting_table', 'IFRS 8 segment reporting table', 'advanced', 'IFRS reporting', 'financial_statement', 'Operating segment revenue, profit, assets, liabilities, and reconciliation.', { standardFramework: 'IFRS', tableKind: 'segment_reporting', columns: ['Segment', 'Revenue', 'Profit', 'Assets', 'Liabilities'], rows: [['Education', '500,000', '80,000', '700,000', '300,000'], ['Technology', '300,000', '60,000', '400,000', '150,000'], ['Total reportable', '800,000', '140,000', '1,100,000', '450,000']], required: ['Identify reportable segments', 'Prepare segment disclosure'] }),
  table('diluted_eps_table', 'Diluted EPS table', 'advanced', 'IFRS reporting', 'case_study', 'IAS 33 diluted EPS using convertible instruments/options adjustment.', { standardFramework: 'IFRS', tableKind: 'diluted_eps', columns: ['Measure', 'Basic', 'Dilutive adjustment', 'Diluted'], rows: [['Earnings', '120,000', 'Add back interest net of tax 8,000', '128,000'], ['Shares', '60,000', 'Convertible shares 20,000', '80,000'], ['EPS', 'K2.00', '', 'K1.60']], required: ['Calculate diluted earnings', 'Calculate diluted shares', 'Calculate diluted EPS'] }),
  table('share_based_payment_expense', 'Share-based payment expense schedule', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IFRS 2 grant-date fair value, vesting, cumulative expense, and annual charge.', { standardFramework: 'IFRS', tableKind: 'share_based_payment_expense', columns: ['Year', 'Expected vested options', 'Fair value', 'Cumulative expense', 'Current year expense'], rows: [['1', '10,000', 'K5', '16,667', '16,667'], ['2', '10,000', 'K5', '33,333', '16,666'], ['3', '10,000', 'K5', '50,000', '16,667']], required: ['Calculate cumulative expense', 'Calculate current year expense'] }),
  table('hedge_accounting_effectiveness', 'Hedge accounting effectiveness table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Hedge item, hedging instrument, risk, effectiveness, OCI/P/L treatment.', { standardFramework: 'IFRS', tableKind: 'hedge_accounting_effectiveness', columns: ['Hedged item', 'Hedging instrument', 'Risk hedged', 'Effective portion', 'Ineffective portion', 'Treatment'], rows: [['Forecast USD purchase', 'Forward contract', 'FX risk', '18,000', '2,000', 'Effective OCI, ineffective P/L']], required: ['Assess hedge effectiveness', 'Classify OCI/P/L treatment'] }),
  table('ifrs9_asset_classification', 'IFRS 9 financial asset classification table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Business model and SPPI test matrix for amortised cost, FVOCI, or FVTPL.', { standardFramework: 'IFRS', tableKind: 'ifrs9_asset_classification', columns: ['Asset', 'Business model', 'SPPI passed?', 'Classification'], rows: [['Trade receivable', 'Hold to collect', 'Yes', 'Amortised cost'], ['Equity investment', 'Hold for strategic reasons', 'N/A', 'FVOCI election or FVTPL'], ['Debt investment trading', 'Sell for short-term gains', 'Yes', 'FVTPL']], required: ['Apply business model test', 'Apply SPPI test', 'Classify asset'] }),
  table('ifrs9_impairment_staging', 'IFRS 9 impairment staging table', 'advanced', 'IFRS reporting', 'case_study', 'Stage 1/2/3 impairment classification and ECL measurement basis.', { standardFramework: 'IFRS', tableKind: 'ifrs9_impairment_staging', columns: ['Instrument', 'Credit risk change', 'Stage', 'ECL basis', 'Interest recognition'], rows: [['Loan A', 'No significant increase', 'Stage 1', '12-month ECL', 'Gross carrying amount'], ['Loan B', 'Significant increase', 'Stage 2', 'Lifetime ECL', 'Gross carrying amount'], ['Loan C', 'Credit-impaired', 'Stage 3', 'Lifetime ECL', 'Net carrying amount']], required: ['Classify impairment stage', 'Choose ECL basis'] }),
  table('convertible_debt_split_accounting', 'Convertible debt split accounting table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Splits convertible debt into liability and equity components.', { standardFramework: 'IFRS', tableKind: 'convertible_debt_split', columns: ['Item', 'Amount'], rows: [['Proceeds received', '100,000'], ['Fair value of liability component', '(85,000)'], ['Equity component', '15,000']], required: ['Calculate liability component', 'Calculate equity component'] }),
  table('provisions_roll_forward', 'Provisions roll-forward schedule', 'advanced', 'IFRS reporting', 'financial_statement', 'Opening provision, additions, utilisation, unwinding discount, reversal, and closing provision.', { standardFramework: 'IFRS', tableKind: 'provisions_roll_forward', columns: ['Item', 'Amount'], rows: [['Opening provision', '30,000'], ['Additional provision', '10,000'], ['Unwinding of discount', '2,000'], ['Utilised during year', '(8,000)'], ['Reversed unused amount', '(4,000)'], ['Closing provision', '30,000']], required: ['Prepare provision movement', 'Explain recognition and reversal'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
