import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const managementDecisionAccountingTables: AccountingTableTemplate[] = [
  table('service_costing_table', 'Service costing table', 'advanced', 'Management accounting', 'case_study', 'Service cost per unit for hospitals, hotels, transport, schools, and service organisations.', { tableKind: 'service_costing', columns: ['Cost item', 'Amount'], rows: [['Staff costs', '120,000'], ['Utilities', '30,000'], ['Depreciation', '20,000'], ['Total service cost', '170,000'], ['Service units', '10,000'], ['Cost per service unit', 'K17']], required: ['Calculate service cost', 'Calculate cost per unit'] }),
  table('transport_operating_cost_statement', 'Transport operating cost statement', 'advanced', 'Management accounting', 'case_study', 'Operating cost per kilometre/passenger for transport businesses.', { tableKind: 'transport_operating_cost', columns: ['Cost item', 'Amount'], rows: [['Fuel', '50,000'], ['Driver wages', '40,000'], ['Repairs', '15,000'], ['Insurance', '10,000'], ['Total cost', '115,000'], ['Kilometres', '25,000'], ['Cost per km', 'K4.60']], required: ['Calculate total operating cost', 'Calculate cost per km'] }),
  table('batch_costing_table', 'Batch costing table', 'advanced', 'Management accounting', 'case_study', 'Batch cost and unit cost for batch production.', { tableKind: 'batch_costing', columns: ['Cost item', 'Amount'], rows: [['Direct materials', '30,000'], ['Direct labour', '18,000'], ['Overheads', '12,000'], ['Batch cost', '60,000'], ['Units in batch', '2,000'], ['Cost per unit', 'K30']], required: ['Calculate batch cost', 'Calculate unit cost'] }),
  table('economic_order_quantity_table', 'Economic order quantity table', 'advanced', 'Inventory control', 'case_study', 'EOQ, ordering cost, holding cost, and total inventory cost.', { tableKind: 'economic_order_quantity', columns: ['Measure', 'Formula/value', 'Result'], rows: [['Annual demand', 'D', '10,000 units'], ['Ordering cost', 'Co', 'K50'], ['Holding cost', 'Ch', 'K2'], ['EOQ', '√(2DCo/Ch)', '707 units']], required: ['Calculate EOQ', 'Explain ordering/holding cost trade-off'] }),
  table('inventory_control_levels', 'Inventory reorder/control levels table', 'advanced', 'Inventory control', 'case_study', 'Reorder level, minimum level, maximum level, average stock level, and reorder quantity.', { tableKind: 'inventory_control_levels', columns: ['Level', 'Formula', 'Result'], rows: [['Reorder level', 'Maximum usage x maximum lead time', '1,000 units'], ['Minimum level', 'Reorder level - normal usage x normal lead time', '400 units'], ['Maximum level', 'Reorder level + reorder quantity - minimum usage x minimum lead time', '1,500 units']], required: ['Calculate stock control levels', 'Explain inventory risk'] }),
  table('make_or_buy_decision', 'Make-or-buy decision table', 'advanced', 'Decision making', 'case_study', 'Compares relevant cost of internal production versus external purchase.', { tableKind: 'make_or_buy_decision', columns: ['Cost item', 'Make', 'Buy'], rows: [['Direct materials', '30,000', ''], ['Direct labour', '20,000', ''], ['Avoidable overheads', '10,000', ''], ['Purchase price', '', '70,000'], ['Relevant cost', '60,000', '70,000']], required: ['Identify relevant costs', 'Choose make or buy'] }),
  table('limiting_factor_product_mix', 'Limiting factor / product mix table', 'advanced', 'Decision making', 'case_study', 'Ranks products by contribution per limiting factor.', { tableKind: 'limiting_factor_product_mix', columns: ['Product', 'Contribution per unit', 'Limiting factor per unit', 'Contribution per limiting factor', 'Rank'], rows: [['A', 'K30', '3 hours', 'K10/hour', '2'], ['B', 'K24', '2 hours', 'K12/hour', '1']], required: ['Calculate contribution per limiting factor', 'Rank products', 'Prepare optimal mix'] }),
  table('relevant_costing_decision', 'Relevant costing decision table', 'advanced', 'Decision making', 'case_study', 'Identifies relevant and irrelevant costs for one-off decisions.', { tableKind: 'relevant_costing_decision', columns: ['Cost item', 'Relevant?', 'Reason', 'Amount'], rows: [['Sunk development cost', 'No', 'Already incurred', '0'], ['Special material purchase', 'Yes', 'Future incremental cost', '20,000'], ['Spare capacity labour', 'No', 'No extra cash flow', '0']], required: ['Identify relevant costs', 'Calculate decision cost'] }),
  table('shutdown_decision_table', 'Shutdown decision table', 'advanced', 'Decision making', 'case_study', 'Compares contribution lost, avoidable fixed costs, and shutdown decision.', { tableKind: 'shutdown_decision', columns: ['Item', 'Continue', 'Shutdown'], rows: [['Contribution', '50,000', '0'], ['Avoidable fixed costs', '(30,000)', '0'], ['Unavoidable fixed costs', '(20,000)', '(20,000)'], ['Net effect', '0', '(20,000)']], required: ['Identify avoidable costs', 'Recommend shutdown or continue'] }),
  table('special_order_pricing', 'Special order pricing table', 'advanced', 'Decision making', 'case_study', 'Minimum acceptable price for a special order using incremental costs.', { tableKind: 'special_order_pricing', columns: ['Cost/revenue item', 'Amount'], rows: [['Direct materials', '30,000'], ['Direct labour', '20,000'], ['Variable overhead', '10,000'], ['Special packaging', '5,000'], ['Minimum price', '65,000']], required: ['Calculate minimum price', 'Consider qualitative factors'] }),
  table('transfer_pricing_table', 'Transfer pricing table', 'advanced', 'Decision making', 'case_study', 'Minimum and maximum transfer price with capacity and market constraints.', { tableKind: 'transfer_pricing', columns: ['Measure', 'Amount'], rows: [['Variable cost', 'K20'], ['Opportunity cost', 'K5'], ['Minimum transfer price', 'K25'], ['External purchase price', 'K35'], ['Negotiation range', 'K25-K35']], required: ['Calculate minimum transfer price', 'Explain negotiation range'] }),
  table('responsibility_performance_report', 'Responsibility accounting performance report', 'advanced', 'Performance management', 'case_study', 'Controllable revenues, costs, variances, and responsibility centre performance.', { tableKind: 'responsibility_performance_report', columns: ['Item', 'Budget', 'Actual', 'Variance', 'Controllable?'], rows: [['Sales', '200,000', '210,000', '10,000 F', 'Yes'], ['Direct labour', '50,000', '55,000', '5,000 A', 'Yes'], ['Allocated head office costs', '20,000', '22,000', '2,000 A', 'No']], required: ['Separate controllable items', 'Evaluate manager performance'] }),
  table('segment_profitability_report', 'Segment profitability report', 'advanced', 'Performance management', 'case_study', 'Segment contribution, traceable fixed costs, and segment margin.', { tableKind: 'segment_profitability_report', columns: ['Segment', 'Revenue', 'Variable costs', 'Contribution', 'Traceable fixed costs', 'Segment margin'], rows: [['Segment A', '300,000', '(180,000)', '120,000', '(50,000)', '70,000'], ['Segment B', '200,000', '(140,000)', '60,000', '(70,000)', '(10,000)']], required: ['Calculate segment margin', 'Recommend continuation or improvement'] }),
  table('balanced_scorecard_table', 'Balanced scorecard table', 'advanced', 'Performance management', 'case_study', 'Financial, customer, internal process, and learning/growth metrics.', { tableKind: 'balanced_scorecard', columns: ['Perspective', 'Objective', 'Measure', 'Target', 'Actual'], rows: [['Financial', 'Improve profitability', 'Net margin', '15%', '12%'], ['Customer', 'Improve satisfaction', 'Rating', '90%', '85%'], ['Internal process', 'Reduce defects', 'Defect rate', '2%', '3%'], ['Learning/growth', 'Improve skills', 'Training hours', '40', '35']], required: ['Interpret performance', 'Recommend improvements'] }),
  table('learning_curve_costing', 'Learning curve costing table', 'advanced', 'Decision making', 'case_study', 'Learning curve average time, total time, and labour cost.', { tableKind: 'learning_curve_costing', columns: ['Units doubled', 'Average time per unit', 'Total time', 'Labour cost'], rows: [['1 unit', '100 hours', '100', 'K5,000'], ['2 units', '80 hours', '160', 'K8,000'], ['4 units', '64 hours', '256', 'K12,800']], required: ['Apply learning rate', 'Calculate labour cost'] }),
  table('target_costing_table', 'Target costing table', 'advanced', 'Strategic management accounting', 'case_study', 'Target cost from market price and required margin.', { tableKind: 'target_costing', columns: ['Item', 'Amount'], rows: [['Target selling price', 'K100'], ['Required profit margin', '25%'], ['Target profit', 'K25'], ['Target cost', 'K75'], ['Current estimated cost', 'K82'], ['Cost gap', 'K7']], required: ['Calculate target cost', 'Identify cost gap'] }),
  table('life_cycle_costing_table', 'Life-cycle costing table', 'advanced', 'Strategic management accounting', 'case_study', 'Costs and revenues across product life cycle.', { tableKind: 'life_cycle_costing', columns: ['Stage', 'Revenue', 'Cost', 'Net cash flow'], rows: [['Development', '0', '(100,000)', '(100,000)'], ['Introduction', '80,000', '(70,000)', '10,000'], ['Growth', '300,000', '(180,000)', '120,000'], ['Decline', '100,000', '(60,000)', '40,000']], required: ['Calculate life-cycle profit', 'Explain strategic decision'] }),
  table('throughput_accounting_table', 'Throughput accounting table', 'advanced', 'Strategic management accounting', 'case_study', 'Throughput per bottleneck hour and ranking.', { tableKind: 'throughput_accounting', columns: ['Product', 'Selling price', 'Material cost', 'Throughput', 'Bottleneck hours', 'Throughput per hour', 'Rank'], rows: [['A', 'K100', 'K40', 'K60', '3', 'K20', '2'], ['B', 'K80', 'K30', 'K50', '2', 'K25', '1']], required: ['Calculate throughput', 'Rank products by bottleneck resource'] }),
  table('environmental_management_accounting', 'Environmental management accounting table', 'advanced', 'Strategic management accounting', 'case_study', 'Environmental costs by prevention, appraisal, internal failure, and external failure.', { tableKind: 'environmental_management_accounting', columns: ['Cost category', 'Example', 'Amount'], rows: [['Prevention', 'Cleaner production training', '15,000'], ['Appraisal', 'Environmental audit', '10,000'], ['Internal failure', 'Waste treatment', '25,000'], ['External failure', 'Fines/cleanup', '40,000']], required: ['Classify environmental costs', 'Recommend cost reduction action'] }),
  table('spoilage_rework_scrap_table', 'Spoilage/rework/scrap accounting table', 'advanced', 'Cost accounting', 'case_study', 'Normal/abnormal spoilage, rework, scrap proceeds, and accounting treatment.', { tableKind: 'spoilage_rework_scrap', columns: ['Item', 'Units/amount', 'Treatment'], rows: [['Normal spoilage', '200 units', 'Include in production cost'], ['Abnormal spoilage', '50 units', 'Charge to P/L'], ['Scrap proceeds', 'K2,000', 'Reduce cost or recognise income']], required: ['Classify spoilage', 'State accounting treatment'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
