import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const publicSectorAccountingTables: AccountingTableTemplate[] = [
  table('fund_accounting_statement', 'Fund accounting statement', 'advanced', 'Public sector / NGO accounting', 'financial_statement', 'Shows opening fund balance, receipts, expenditure, transfers, and closing fund balance.', { currency: 'ZMW', standardFramework: 'Fund accounting format', tableKind: 'fund_accounting_statement', columns: ['Fund', 'Opening balance', 'Receipts', 'Expenditure', 'Transfers', 'Closing balance'], rows: [['General fund', '50,000', '120,000', '(100,000)', '(10,000)', '60,000'], ['Restricted donor fund', '20,000', '80,000', '(60,000)', '', '40,000']], required: ['Calculate fund balances', 'Separate restricted and unrestricted funds'] }),
  table('budget_vs_actual_statement', 'Statement of budget vs actual', 'advanced', 'Public sector / NGO accounting', 'case_study', 'Compares approved budget to actual revenue/expenditure and variance.', { tableKind: 'budget_vs_actual', columns: ['Line item', 'Budget', 'Actual', 'Variance', 'Explanation'], rows: [['Tuition/grants', '500,000', '480,000', '20,000 adverse', 'Lower enrolment'], ['Salaries', '250,000', '260,000', '10,000 adverse', 'New hires'], ['Materials', '80,000', '70,000', '10,000 favourable', 'Delayed procurement']], required: ['Calculate variance', 'Explain budget performance'] }),
  table('donor_grant_utilisation', 'Donor grant utilisation table', 'advanced', 'Public sector / NGO accounting', 'case_study', 'Tracks donor grant receipts, eligible expenditure, ineligible expenditure, and unspent balance.', { tableKind: 'donor_grant_utilisation', columns: ['Grant', 'Amount received', 'Eligible expenditure', 'Ineligible expenditure', 'Unspent balance'], rows: [['STEM Lab Grant', '200,000', '(150,000)', '(5,000)', '45,000'], ['Scholarship Fund', '100,000', '(80,000)', '0', '20,000']], required: ['Calculate utilisation', 'Identify ineligible expenditure'] }),
  table('restricted_unrestricted_funds', 'Restricted/unrestricted funds table', 'advanced', 'Public sector / NGO accounting', 'financial_statement', 'Separates restricted funds from unrestricted operational funds.', { currency: 'ZMW', tableKind: 'restricted_unrestricted_funds', columns: ['Item', 'Restricted funds', 'Unrestricted funds', 'Total'], rows: [['Opening balance', '80,000', '50,000', '130,000'], ['Income', '120,000', '200,000', '320,000'], ['Expenditure', '(90,000)', '(180,000)', '(270,000)'], ['Closing balance', '110,000', '70,000', '180,000']], required: ['Classify funds', 'Calculate closing balances'] }),
  table('public_sector_appropriation_account', 'Public sector appropriation account', 'advanced', 'Public sector accounting', 'case_study', 'Appropriation, releases, expenditure, commitments, and balance available.', { tableKind: 'public_sector_appropriation_account', columns: ['Vote/head', 'Approved budget', 'Funds released', 'Actual expenditure', 'Commitments', 'Available balance'], rows: [['Education materials', '500,000', '400,000', '(320,000)', '(50,000)', '30,000'], ['Maintenance', '200,000', '160,000', '(140,000)', '(10,000)', '10,000']], required: ['Track appropriation usage', 'Calculate available balance'] }),
  table('commitment_control_table', 'Commitment control table', 'advanced', 'Public sector accounting', 'case_study', 'Controls purchase commitments before cash payment to avoid overspending budget.', { tableKind: 'commitment_control', columns: ['Purchase request', 'Budget line', 'Budget available', 'Commitment', 'Remaining budget', 'Approved?'], rows: [['PR001 textbooks', 'Materials', '100,000', '30,000', '70,000', 'Yes'], ['PR002 repairs', 'Maintenance', '10,000', '25,000', '(15,000)', 'No']], required: ['Check budget availability', 'Approve or reject commitment'] }),
  table('procurement_payment_voucher_register', 'Procurement/payment voucher register', 'advanced', 'Public sector accounting', 'case_study', 'Tracks procurement request, purchase order, invoice, voucher, approval, and payment.', { tableKind: 'payment_voucher_register', columns: ['Voucher', 'Supplier', 'PO number', 'Invoice', 'Amount', 'Approved by', 'Paid?'], rows: [['PV001', 'Zed Supplies', 'PO101', 'INV45', '25,000', 'Head of Finance', 'Yes'], ['PV002', 'Ndola Printers', 'PO102', 'INV46', '8,000', 'Pending', 'No']], required: ['Verify voucher completeness', 'Identify unpaid vouchers'] }),
  table('asset_verification_register', 'Asset verification register', 'advanced', 'Public sector / NGO accounting', 'case_study', 'Asset register with physical verification status and variances.', { tableKind: 'asset_verification_register', columns: ['Asset tag', 'Description', 'Book location', 'Physical location', 'Condition', 'Variance'], rows: [['FA001', 'Laptop', 'ICT Lab', 'ICT Lab', 'Good', 'None'], ['FA002', 'Projector', 'Lecture Room 2', 'Missing', 'Unknown', 'Investigate']], required: ['Verify assets', 'Report missing/damaged assets'] }),
  table('school_church_ngo_fund_accountability', 'School/church/NGO fund accountability table', 'advanced', 'Public sector / NGO accounting', 'case_study', 'Receipts, authorised expenditure, supporting documents, and accountability balance.', { tableKind: 'ngo_fund_accountability', columns: ['Fund/activity', 'Amount received', 'Supported expenditure', 'Unsupported expenditure', 'Balance/accountability issue'], rows: [['Youth programme', '50,000', '(42,000)', '(3,000)', '5,000 unspent'], ['Building fund', '100,000', '(80,000)', '0', '20,000 bank balance']], required: ['Check supporting documents', 'Calculate accountability balance'] }),
  table('project_expenditure_report', 'Project expenditure report', 'advanced', 'Public sector / NGO accounting', 'case_study', 'Project budget, expenditure by category, variance, and burn rate.', { tableKind: 'project_expenditure_report', columns: ['Budget category', 'Approved budget', 'Actual to date', 'Variance', 'Burn rate'], rows: [['Training', '100,000', '75,000', '25,000', '75%'], ['Equipment', '200,000', '180,000', '20,000', '90%'], ['Monitoring', '50,000', '20,000', '30,000', '40%']], required: ['Calculate project variance', 'Interpret burn rate'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
