import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const supplementalAccountingTables: AccountingTableTemplate[] = [
  table('chart_of_accounts_classification', 'Chart of accounts classification table', 'beginner', 'Foundations', 'concept', 'Classifies accounts by asset, liability, equity, income, expense, normal balance, and statement destination.', { concept: 'Chart of accounts classification', tableKind: 'chart_of_accounts_classification', columns: ['Account', 'Class', 'Normal balance', 'Statement', 'Example increase'], rows: [['Cash', 'Asset', 'Debit', 'Statement of financial position', 'Debit Cash'], ['Capital', 'Equity', 'Credit', 'Statement of financial position', 'Credit Capital'], ['Sales', 'Income', 'Credit', 'Income statement', 'Credit Sales'], ['Rent', 'Expense', 'Debit', 'Income statement', 'Debit Rent']], required: ['Classify each account', 'State the normal balance', 'Explain the financial statement destination'] }),
  table('debit_credit_rules_grid', 'Debit and credit rules grid', 'beginner', 'Double entry', 'concept', 'Rules table showing what increases and decreases each class of account.', { concept: 'Debit and credit rules', tableKind: 'debit_credit_rules_grid', columns: ['Account class', 'Increase', 'Decrease', 'Normal balance'], rows: [['Assets', 'Debit', 'Credit', 'Debit'], ['Expenses', 'Debit', 'Credit', 'Debit'], ['Drawings', 'Debit', 'Credit', 'Debit'], ['Liabilities', 'Credit', 'Debit', 'Credit'], ['Capital', 'Credit', 'Debit', 'Credit'], ['Income', 'Credit', 'Debit', 'Credit']] }),
  table('ledger_balance_extraction', 'Ledger balance extraction table', 'beginner', 'Ledger posting', 'case_study', 'Shows how ledger balances are extracted before preparing a trial balance.', { tableKind: 'ledger_balance_extraction', columns: ['Ledger account', 'Debit total', 'Credit total', 'Balance side', 'Balance amount'], rows: [['Cash', '15,000', '6,000', 'Debit', '9,000'], ['Capital', '', '12,000', 'Credit', '12,000'], ['Purchases', '3,000', '', 'Debit', '3,000']], required: ['Total both sides', 'Find the balance side', 'Transfer balances to the trial balance'] }),
  table('opening_entry_table', 'Opening entry table', 'beginner', 'Opening balances', 'journal_entry', 'Introduces opening assets, liabilities, and capital as a journal entry.', { currency: 'ZMW', tableKind: 'opening_entry', question: 'Open the books with Cash K8,000, Inventory K4,000, Payables K2,000, and Capital as the balancing figure.', rows: [{ account: 'Cash', debit: 8000, credit: 0 }, { account: 'Inventory', debit: 4000, credit: 0 }, { account: 'Accounts Payable', debit: 0, credit: 2000 }, { account: 'Capital', debit: 0, credit: 10000 }] }, { rows: [{ account: 'Cash', debit: 8000, credit: 0 }, { account: 'Inventory', debit: 4000, credit: 0 }, { account: 'Accounts Payable', debit: 0, credit: 2000 }, { account: 'Capital', debit: 0, credit: 10000 }] }),
  table('closing_entries_table', 'Closing entries table', 'beginner', 'Final accounts', 'journal_entry', 'Closes income and expense accounts to profit or loss.', { currency: 'ZMW', tableKind: 'closing_entries', question: 'Close sales and expenses to the income statement.', rows: [{ account: 'Sales', debit: 12000, credit: 0 }, { account: 'Income Statement', debit: 0, credit: 12000 }, { account: 'Income Statement', debit: 7000, credit: 0 }, { account: 'Expenses', debit: 0, credit: 7000 }] }),
  table('vat_control_account', 'VAT control account', 'intermediate', 'VAT / sales tax', 'ledger', 'Tracks output VAT, input VAT, payments/refunds, and closing VAT balance.', { currency: 'ZMW', tableKind: 'vat_control_account', accountName: 'VAT Control Account', debitEntries: [{ details: 'Input VAT on purchases', amount: 1800 }, { details: 'Bank payment to tax authority', amount: 1200 }], creditEntries: [{ details: 'Output VAT on sales', amount: 3000 }] }),
  table('receivables_ledger_schedule', 'Receivables ledger schedule', 'intermediate', 'Subsidiary ledgers', 'case_study', 'Customer-by-customer receivables ledger balances reconciled to the control account.', { tableKind: 'receivables_ledger_schedule', columns: ['Customer', 'Opening balance', 'Credit sales', 'Receipts', 'Returns', 'Discount', 'Closing balance'], rows: [['Banda Stores', '2,000', '3,500', '(2,500)', '(400)', '(100)', '2,500'], ['Copper Mart', '1,500', '4,000', '(3,000)', '', '(200)', '2,300']], required: ['Calculate each customer balance', 'Agree total to receivables control account'] }),
  table('payables_ledger_schedule', 'Payables ledger schedule', 'intermediate', 'Subsidiary ledgers', 'case_study', 'Supplier-by-supplier payables ledger balances reconciled to the control account.', { tableKind: 'payables_ledger_schedule', columns: ['Supplier', 'Opening balance', 'Credit purchases', 'Payments', 'Returns', 'Discount', 'Closing balance'], rows: [['Zed Supplies', '1,800', '2,500', '(2,000)', '(300)', '(100)', '1,900'], ['Ndola Wholesalers', '2,200', '3,000', '(2,500)', '', '(150)', '2,550']], required: ['Calculate each supplier balance', 'Agree total to payables control account'] }),
  table('depreciation_asset_register', 'Depreciation and asset register', 'intermediate', 'Non-current assets', 'depreciation', 'Shows asset cost, accumulated depreciation, annual charge, carrying amount, and disposal status.', { currency: 'ZMW', tableKind: 'asset_register', columns: ['Asset', 'Cost', 'Accumulated depreciation b/f', 'Current depreciation', 'Accumulated depreciation c/f', 'Carrying amount'], rows: [['Motor vehicle', '50,000', '10,000', '8,000', '18,000', '32,000'], ['Equipment', '30,000', '6,000', '4,800', '10,800', '19,200']], cost: 50000, residualValue: 10000, usefulLifeYears: 5, method: 'straight_line', required: ['Calculate depreciation', 'Update accumulated depreciation', 'Calculate carrying amount'] }),
  table('asset_disposal_account', 'Asset disposal account', 'intermediate', 'Non-current assets', 'ledger', 'Disposal account showing cost, accumulated depreciation, proceeds, and profit/loss on disposal.', { currency: 'ZMW', tableKind: 'asset_disposal_account', accountName: 'Asset Disposal Account', debitEntries: [{ details: 'Motor vehicle at cost', amount: 40000 }], creditEntries: [{ details: 'Accumulated depreciation', amount: 22000 }, { details: 'Bank proceeds', amount: 15000 }, { details: 'Loss on disposal', amount: 3000 }] }),
  table('inventory_stock_card_fifo', 'Inventory stock card FIFO', 'intermediate', 'Inventory', 'inventory', 'Stock card showing receipts, issues, balance quantities, unit costs, and FIFO cost layers.', { tableKind: 'inventory_stock_card_fifo', method: 'FIFO', transactions: [{ type: 'purchase', units: 100, unitCost: 20 }, { type: 'purchase', units: 50, unitCost: 24 }, { type: 'sale', units: 120 }], columns: ['Date', 'Receipts qty/cost', 'Issues qty/cost', 'Balance layers'], rows: [['Jan 1', '100 @ K20', '', '100 @ K20'], ['Jan 5', '50 @ K24', '', '100 @ K20; 50 @ K24'], ['Jan 10', '', '120 units FIFO', '30 @ K24']], required: ['Calculate cost of issues', 'Calculate closing inventory'] }),
  table('suspense_account_reconciliation', 'Suspense account reconciliation', 'intermediate', 'Error correction', 'ledger', 'Suspense account used to clear one-sided errors and restore trial balance agreement.', { currency: 'ZMW', tableKind: 'suspense_account', accountName: 'Suspense Account', debitEntries: [{ details: 'Correction of sales undercast', amount: 700 }], creditEntries: [{ details: 'Difference on trial balance', amount: 700 }], required: ['Identify one-sided errors', 'Post correction to suspense', 'Clear suspense balance'] }),
  table('incomplete_records_statement_of_affairs', 'Incomplete records statement of affairs', 'intermediate', 'Incomplete records', 'case_study', 'Opening and closing statement of affairs for calculating capital and profit.', { tableKind: 'statement_of_affairs', columns: ['Item', 'Opening', 'Closing'], rows: [['Cash', '3,000', '4,500'], ['Inventory', '8,000', '9,500'], ['Receivables', '5,000', '6,500'], ['Payables', '(4,000)', '(3,500)'], ['Capital', '12,000', '17,000']], required: ['Calculate opening capital', 'Calculate closing capital', 'Adjust for drawings and additional capital to find profit'] }),
  table('markup_margin_reconstruction', 'Markup and margin reconstruction table', 'intermediate', 'Incomplete records', 'case_study', 'Uses markup or margin to reconstruct sales, cost of goods sold, or missing inventory.', { tableKind: 'markup_margin_reconstruction', columns: ['Measure', 'Amount'], rows: [['Cost of goods sold', '40,000'], ['Markup', '25% on cost'], ['Sales', '50,000'], ['Gross profit', '10,000']], required: ['Distinguish markup from margin', 'Reconstruct missing sales or cost figure'] }),
  table('club_income_and_expenditure', 'Club income and expenditure account', 'intermediate', 'Non-profit accounts', 'financial_statement', 'Non-profit income and expenditure format with subscriptions and expenses.', { currency: 'ZMW', standardFramework: 'Non-profit accounting format', statementType: 'income_and_expenditure_account', businessName: 'UnivAI Sports Club', period: 'Year ended 31 December 2026', tableKind: 'income_and_expenditure_account', sections: [{ title: 'Income', items: [{ name: 'Subscriptions income', amount: 30000 }, { name: 'Donations', amount: 5000 }] }, { title: 'Expenditure', items: [{ name: 'Ground maintenance', amount: 12000 }, { name: 'Salaries', amount: 10000 }] }] }),
  table('subscriptions_account', 'Subscriptions account', 'intermediate', 'Non-profit accounts', 'ledger', 'Subscriptions control account calculating income for the year from cash, arrears, and advance subscriptions.', { currency: 'ZMW', tableKind: 'subscriptions_account', accountName: 'Subscriptions Account', debitEntries: [{ details: 'Balance b/d arrears', amount: 2000 }, { details: 'Income and expenditure account', amount: 30000 }, { details: 'Balance c/d advance', amount: 1000 }], creditEntries: [{ details: 'Balance b/d advance', amount: 1500 }, { details: 'Bank', amount: 30500 }, { details: 'Balance c/d arrears', amount: 1000 }] }),
  table('departmental_trading_account', 'Departmental trading account', 'advanced', 'Departmental accounts', 'financial_statement', 'Compares sales, cost of sales, gross profit, and expenses across departments.', { currency: 'ZMW', standardFramework: 'Departmental reporting format', tableKind: 'departmental_trading_account', columns: ['Item', 'Department A', 'Department B', 'Total'], rows: [['Sales', '80,000', '60,000', '140,000'], ['Cost of sales', '(48,000)', '(42,000)', '(90,000)'], ['Gross profit', '32,000', '18,000', '50,000'], ['Allocated expenses', '(12,000)', '(9,000)', '(21,000)']], required: ['Calculate departmental gross profit', 'Allocate expenses', 'Compare department performance'] }),
  table('branch_account', 'Branch account', 'advanced', 'Branch accounts', 'ledger', 'Branch account showing goods sent, returns, remittances, expenses, inventory, and branch profit.', { currency: 'ZMW', tableKind: 'branch_account', accountName: 'Branch Account', debitEntries: [{ details: 'Goods sent to branch', amount: 50000 }, { details: 'Branch expenses paid by head office', amount: 8000 }], creditEntries: [{ details: 'Cash remitted by branch', amount: 42000 }, { details: 'Closing inventory at branch', amount: 10000 }, { details: 'Branch profit', amount: 6000 }] }),
  table('process_costing_statement', 'Process costing statement', 'advanced', 'Cost accounting', 'case_study', 'Process account with input, normal loss, abnormal loss/gain, equivalent units, and cost per unit.', { tableKind: 'process_costing_statement', columns: ['Item', 'Units', 'Cost'], rows: [['Input', '10,000', '100,000'], ['Normal loss', '(500)', '0'], ['Abnormal loss', '(200)', '(2,000)'], ['Output', '9,300', '98,000']], required: ['Calculate expected output', 'Identify abnormal loss or gain', 'Calculate cost per unit'] }),
  table('job_cost_card', 'Job cost card', 'advanced', 'Cost accounting', 'case_study', 'Job costing card for direct materials, direct labour, overhead absorption, total cost, and profit.', { tableKind: 'job_cost_card', columns: ['Cost element', 'Amount'], rows: [['Direct materials', '12,000'], ['Direct labour', '8,000'], ['Production overhead absorbed', '6,000'], ['Total production cost', '26,000'], ['Profit markup', '6,500'], ['Selling price', '32,500']], required: ['Calculate job cost', 'Apply overhead absorption', 'Calculate selling price'] }),
  table('marginal_absorption_reconciliation', 'Marginal vs absorption costing reconciliation', 'advanced', 'Management accounting', 'case_study', 'Reconciles profit difference caused by fixed overhead in inventory.', { tableKind: 'marginal_absorption_reconciliation', columns: ['Item', 'Amount'], rows: [['Profit under marginal costing', '25,000'], ['Fixed overhead in closing inventory', '3,000'], ['Fixed overhead in opening inventory', '(1,000)'], ['Profit under absorption costing', '27,000']], required: ['Explain why profits differ', 'Reconcile marginal and absorption profit'] }),
  table('break_even_cvp_table', 'Break-even / CVP table', 'advanced', 'Management accounting', 'case_study', 'Contribution, break-even units, margin of safety, target profit, and profit-volume logic.', { tableKind: 'break_even_cvp_table', columns: ['Measure', 'Formula', 'Result'], rows: [['Contribution per unit', 'Selling price - variable cost', 'K40'], ['Break-even units', 'Fixed costs / contribution per unit', '2,500 units'], ['Margin of safety', 'Expected sales - break-even sales', '1,000 units']], required: ['Calculate contribution', 'Calculate break-even point', 'Interpret margin of safety'] }),
  table('flexible_budget_statement', 'Flexible budget statement', 'advanced', 'Budgeting', 'budgeting', 'Flexes budgeted costs for actual activity and compares against actual cost.', { tableKind: 'flexible_budget_statement', columns: ['Cost item', 'Budget at actual activity', 'Actual cost', 'Variance', 'F/A'], rows: [['Materials', '40,000', '42,500', '2,500', 'A'], ['Labour', '30,000', '28,000', '2,000', 'F'], ['Fixed overhead', '20,000', '21,000', '1,000', 'A']], required: ['Flex the budget', 'Compare actual cost', 'Explain variances'] }),
  table('lease_liability_amortisation_schedule', 'Lease liability amortisation schedule', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IFRS lease liability schedule with opening liability, interest, payments, and closing liability.', { standardFramework: 'IFRS', evidenceStandard: 'Apply IFRS lease recognition and subsequent measurement.', tableKind: 'lease_liability_schedule', columns: ['Year', 'Opening liability', 'Interest', 'Payment', 'Closing liability'], rows: [['1', '100,000', '10,000', '(30,000)', '80,000'], ['2', '80,000', '8,000', '(30,000)', '58,000']], required: ['Calculate finance cost', 'Calculate closing liability', 'Explain statement presentation'] }),
  table('provision_contingency_matrix', 'Provision and contingency matrix', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'IAS 37-style decision table for provisions, contingent liabilities, and disclosures.', { standardFramework: 'IFRS', evidenceStandard: 'Professional judgement on obligation, probability, reliable estimate, and disclosure.', tableKind: 'provision_contingency_matrix', columns: ['Case', 'Present obligation?', 'Probable outflow?', 'Reliable estimate?', 'Accounting treatment'], rows: [['Court case likely to be lost', 'Yes', 'Yes', 'Yes', 'Recognise provision'], ['Possible warranty claim', 'Possible', 'Not probable', 'Uncertain', 'Disclose contingent liability']], required: ['Classify each case', 'Explain recognition or disclosure treatment'] }),
  table('deferred_tax_working', 'Deferred tax working table', 'advanced', 'IFRS reporting', 'tax_computation', 'Temporary differences, tax base, carrying amount, deferred tax asset/liability, and movement.', { jurisdiction: 'General IFRS tax basis', taxYear: '2026', evidenceStandard: 'Explain temporary differences and deferred tax movement.', tableKind: 'deferred_tax_working', columns: ['Item', 'Carrying amount', 'Tax base', 'Temporary difference', 'Deferred tax effect'], rows: [['Equipment', '80,000', '60,000', '20,000 taxable', 'Deferred tax liability'], ['Allowance for doubtful debts', '5,000', '0', '5,000 deductible', 'Deferred tax asset']], required: ['Identify taxable/deductible temporary difference', 'Calculate deferred tax movement'] }),
  table('financial_instrument_amortised_cost', 'Financial instrument amortised cost table', 'advanced', 'IFRS reporting', 'ifrs_treatment', 'Amortised cost schedule using effective interest method.', { standardFramework: 'IFRS', evidenceStandard: 'Apply effective interest method and financial instrument measurement.', tableKind: 'amortised_cost_schedule', columns: ['Period', 'Opening carrying amount', 'Effective interest', 'Cash received/paid', 'Closing carrying amount'], rows: [['1', '95,000', '9,500', '(8,000)', '96,500'], ['2', '96,500', '9,650', '(8,000)', '98,150']], required: ['Calculate effective interest', 'Update carrying amount', 'Explain amortised cost treatment'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
