export type AccountingTableLevel = 'beginner' | 'intermediate' | 'advanced' | 'professional';

export type AccountingTableTemplate = {
  id: string;
  label: string;
  level: AccountingTableLevel;
  area: string;
  accountingType: string;
  description: string;
  data: Record<string, unknown>;
  expectedAnswer?: Record<string, unknown>;
};

export const beginnerAccountingTables: AccountingTableTemplate[] = [
  table('accounting_equation_table', 'Accounting equation table', 'beginner', 'Foundations', 'concept', 'Shows how each transaction keeps Assets = Liabilities + Equity.', {
    concept: 'Accounting equation table',
    explanation: 'Track each transaction effect on assets, liabilities, and equity.',
    tableKind: 'accounting_equation',
    columns: ['Transaction', 'Assets', 'Liabilities', 'Equity', 'Equation check'],
    rows: [['Owner invests cash', '+10,000', '0', '+10,000', 'Balanced'], ['Buy goods for cash', 'Inventory +2,000; Cash -2,000', '0', '0', 'Balanced']],
  }),
  table('source_document_register', 'Source document register', 'beginner', 'Books of original entry', 'case_study', 'Maps invoices, receipts, credit notes, and payment vouchers to books of original entry.', {
    caseTitle: 'Source document register', tableKind: 'source_document_register', columns: ['Document', 'Transaction type', 'Book of original entry', 'Ledger affected'],
    rows: [['Sales invoice', 'Credit sale', 'Sales day book', 'Receivables ledger'], ['Purchase invoice', 'Credit purchase', 'Purchases day book', 'Payables ledger'], ['Receipt', 'Cash received', 'Cash book', 'Cash/Bank']],
    required: ['Classify each source document', 'Explain why the book of original entry is appropriate'],
  }),
  table('journal_narration_table', 'General journal with narration', 'beginner', 'Double entry', 'journal_entry', 'Journal table with date, account, debit, credit, and narration.', {
    currency: 'ZMW', tableKind: 'general_journal', question: 'Record owner capital introduced into the business.',
    columns: ['Date', 'Account', 'Debit', 'Credit', 'Narration'], rows: [{ account: 'Cash', debit: 10000, credit: 0, narration: 'Being capital introduced' }, { account: 'Capital', debit: 0, credit: 10000, narration: 'Being capital introduced' }],
  }, { rows: [{ account: 'Cash', debit: 10000, credit: 0 }, { account: 'Capital', debit: 0, credit: 10000 }] }),
  table('ledger_t_account', 'Ledger / T-account table', 'beginner', 'Ledger posting', 'ledger', 'T-account format for posting debit and credit entries.', {
    currency: 'ZMW', tableKind: 't_account', accountName: 'Cash Account', debitEntries: [{ date: '2026-01-01', details: 'Capital', amount: 10000 }], creditEntries: [{ date: '2026-01-03', details: 'Purchases', amount: 2500 }],
  }),
  table('simple_trial_balance', 'Simple trial balance', 'beginner', 'Trial balance', 'trial_balance', 'Basic debit and credit listing to test ledger arithmetic accuracy.', {
    currency: 'ZMW', tableKind: 'trial_balance', title: 'Trial Balance as at 31 January 2026', accounts: [{ name: 'Cash', debit: 7500, credit: 0 }, { name: 'Purchases', debit: 2500, credit: 0 }, { name: 'Capital', debit: 0, credit: 10000 }],
  }, { accounts: [{ name: 'Cash', debit: 7500, credit: 0 }, { name: 'Purchases', debit: 2500, credit: 0 }, { name: 'Capital', debit: 0, credit: 10000 }] }),
  table('simple_income_statement', 'Simple income statement', 'beginner', 'Financial statements', 'financial_statement', 'Beginner profit statement with revenue, expenses, and profit.', {
    currency: 'ZMW', standardFramework: 'Basic financial statement format', tableKind: 'income_statement', statementType: 'income_statement', businessName: 'Muloongo Traders', period: 'Month ended 31 January 2026', sections: [{ title: 'Revenue', items: [{ name: 'Sales', amount: 12000 }] }, { title: 'Expenses', items: [{ name: 'Rent', amount: 2000 }, { name: 'Wages', amount: 3000 }] }],
  }),
  table('simple_statement_of_financial_position', 'Simple statement of financial position', 'beginner', 'Financial statements', 'financial_statement', 'Assets, equity, and liabilities in beginner statement format.', {
    currency: 'ZMW', standardFramework: 'Basic financial statement format', tableKind: 'statement_of_financial_position', statementType: 'statement_of_financial_position', businessName: 'Muloongo Traders', period: 'As at 31 January 2026', sections: [{ title: 'Assets', items: [{ name: 'Cash', amount: 7000 }, { name: 'Inventory', amount: 3000 }] }, { title: 'Equity and liabilities', items: [{ name: 'Capital', amount: 10000 }] }],
  }),
];

export const intermediateAccountingTables: AccountingTableTemplate[] = [
  table('three_column_cash_book', 'Three-column cash book', 'intermediate', 'Cash book', 'case_study', 'Cash, bank, and discount columns for receipts and payments.', { tableKind: 'three_column_cash_book', caseTitle: 'Three-column cash book', columns: ['Date', 'Details', 'Discount allowed', 'Cash', 'Bank', 'Date', 'Details', 'Discount received', 'Cash', 'Bank'], rows: [['Jan 1', 'Balance b/d', '', '', '8,000', 'Jan 3', 'Rent', '', '', '1,000'], ['Jan 5', 'Receivables', '200', '', '2,800', 'Jan 8', 'Payables', '150', '', '2,350']], required: ['Balance the cash book', 'Post discount totals to the ledger'] }),
  table('petty_cash_imprest', 'Petty cash imprest table', 'intermediate', 'Petty cash', 'case_study', 'Petty cash analysis columns and reimbursement calculation.', { tableKind: 'petty_cash_imprest', caseTitle: 'Petty cash imprest system', columns: ['Date', 'Voucher', 'Details', 'Total paid', 'Postage', 'Transport', 'Stationery', 'Sundry'], rows: [['Jan 2', 'V01', 'Bus fare', '80', '', '80', '', ''], ['Jan 4', 'V02', 'Envelopes', '50', '50', '', '', ''], ['Jan 6', 'V03', 'Pens', '120', '', '', '120', '']], required: ['Analyse petty cash payments', 'Calculate reimbursement required'] }),
  table('sales_day_book', 'Sales day book', 'intermediate', 'Books of original entry', 'case_study', 'Credit sales listing before posting to receivables and sales ledger.', { tableKind: 'sales_day_book', columns: ['Date', 'Invoice number', 'Customer', 'Net amount', 'VAT', 'Gross amount'], rows: [['Jan 3', 'S001', 'Banda Stores', '2,000', '320', '2,320'], ['Jan 7', 'S002', 'Copper Mart', '3,500', '560', '4,060']], required: ['Post total sales to the general ledger', 'Post each customer to the receivables ledger'] }),
  table('purchases_day_book', 'Purchases day book', 'intermediate', 'Books of original entry', 'case_study', 'Credit purchases listing before posting to payables and purchases ledger.', { tableKind: 'purchases_day_book', columns: ['Date', 'Invoice number', 'Supplier', 'Net amount', 'VAT', 'Gross amount'], rows: [['Jan 4', 'P101', 'Zed Supplies', '1,800', '288', '2,088'], ['Jan 9', 'P102', 'Ndola Wholesalers', '2,200', '352', '2,552']], required: ['Post total purchases', 'Post supplier balances'] }),
  table('returns_day_books', 'Returns inwards/outwards books', 'intermediate', 'Books of original entry', 'case_study', 'Sales returns and purchase returns analysis.', { tableKind: 'returns_day_books', columns: ['Date', 'Credit note', 'Party', 'Reason', 'Net', 'VAT', 'Gross'], rows: [['Jan 10', 'CN01', 'Banda Stores', 'Damaged goods returned by customer', '400', '64', '464'], ['Jan 12', 'CN02', 'Zed Supplies', 'Goods returned to supplier', '300', '48', '348']], required: ['Identify returns inwards and returns outwards', 'Post returns to correct ledgers'] }),
  table('receivables_control_account', 'Receivables control account', 'intermediate', 'Control accounts', 'ledger', 'Control account reconciling opening balance, credit sales, receipts, discounts, returns, and closing balance.', { currency: 'ZMW', tableKind: 'receivables_control_account', accountName: 'Receivables Control Account', debitEntries: [{ details: 'Balance b/d', amount: 6000 }, { details: 'Credit sales', amount: 12000 }], creditEntries: [{ details: 'Bank', amount: 9000 }, { details: 'Discount allowed', amount: 400 }, { details: 'Sales returns', amount: 600 }, { details: 'Balance c/d', amount: 8000 }] }),
  table('payables_control_account', 'Payables control account', 'intermediate', 'Control accounts', 'ledger', 'Control account reconciling purchases, payments, discounts received, returns, and closing balance.', { currency: 'ZMW', tableKind: 'payables_control_account', accountName: 'Payables Control Account', debitEntries: [{ details: 'Bank', amount: 7000 }, { details: 'Discount received', amount: 350 }, { details: 'Purchase returns', amount: 650 }, { details: 'Balance c/d', amount: 5000 }], creditEntries: [{ details: 'Balance b/d', amount: 5000 }, { details: 'Credit purchases', amount: 8000 }] }),
  table('bank_reconciliation_statement', 'Bank reconciliation statement', 'intermediate', 'Bank reconciliation', 'bank_reconciliation', 'Adjusted cash book and adjusted bank statement balances.', { currency: 'ZMW', tableKind: 'bank_reconciliation_statement', cashBookBalance: 8200, bankStatementBalance: 9500, additions: [{ label: 'Direct deposit', amount: 1200 }], deductions: [{ label: 'Bank charges', amount: 300 }], uncreditedDeposits: [{ label: 'Deposit not yet credited', amount: 1000 }], unpresentedCheques: [{ label: 'Cheque not yet presented', amount: 1400 }] }, { adjustedCashBookBalance: 9100, adjustedBankStatementBalance: 9100 }),
  table('accruals_prepayments_schedule', 'Accruals and prepayments schedule', 'intermediate', 'Adjustments', 'case_study', 'Schedule for expense paid, amount used, accrued, prepaid, and income statement charge.', { tableKind: 'accruals_prepayments_schedule', columns: ['Item', 'Paid during year', 'Opening accrual/prepayment', 'Closing accrual/prepayment', 'Income statement amount', 'Statement of financial position amount'], rows: [['Rent', '12,000', '0', '2,000 accrual', '14,000', '2,000 liability'], ['Insurance', '6,000', '0', '1,500 prepayment', '4,500', '1,500 asset']], required: ['Calculate expense for the year', 'Classify closing balances as assets or liabilities'] }),
  table('bad_debts_allowance_schedule', 'Bad debts and allowance schedule', 'intermediate', 'Adjustments', 'case_study', 'Receivables, bad debts written off, allowance movement, and net receivables.', { tableKind: 'bad_debts_allowance_schedule', columns: ['Receivables', 'Bad debts written off', 'Adjusted receivables', 'Allowance rate', 'Allowance required', 'Movement'], rows: [['20,000', '1,000', '19,000', '5%', '950', 'Compare with opening allowance']], required: ['Calculate bad debt expense', 'Calculate closing allowance', 'Show net receivables'] }),
  table('adjusted_trial_balance', 'Adjusted trial balance', 'intermediate', 'Worksheet', 'trial_balance', 'Trial balance after accruals, prepayments, depreciation, inventory, and allowance adjustments.', { currency: 'ZMW', tableKind: 'adjusted_trial_balance', title: 'Adjusted Trial Balance', accounts: [{ name: 'Sales', debit: 0, credit: 50000 }, { name: 'Purchases', debit: 25000, credit: 0 }, { name: 'Rent expense', debit: 14000, credit: 0 }, { name: 'Insurance expense', debit: 4500, credit: 0 }, { name: 'Capital', debit: 0, credit: 43500 }] }),
];

export const advancedAccountingTables: AccountingTableTemplate[] = [
  table('ten_column_worksheet', 'Ten-column accounting worksheet', 'advanced', 'Worksheet', 'case_study', 'Unadjusted trial balance, adjustments, adjusted trial balance, income statement, and statement of financial position columns.', { tableKind: 'ten_column_worksheet', columns: ['Account', 'TB Dr', 'TB Cr', 'Adj Dr', 'Adj Cr', 'ATB Dr', 'ATB Cr', 'IS Dr', 'IS Cr', 'SFP Dr/Cr'], rows: [['Sales', '', '80,000', '', '', '', '80,000', '', '80,000', ''], ['Rent', '10,000', '', '2,000', '', '12,000', '', '12,000', '', ''], ['Prepaid insurance', '', '', '1,500', '', '1,500', '', '', '', '1,500 Dr']], required: ['Complete adjustments', 'Extend balances to financial statements', 'Calculate profit and closing capital'] }),
  table('manufacturing_account', 'Manufacturing account', 'advanced', 'Manufacturing accounts', 'financial_statement', 'Prime cost, factory overheads, work-in-progress, and cost of production.', { currency: 'ZMW', standardFramework: 'Management accounting format', tableKind: 'manufacturing_account', statementType: 'manufacturing_account', businessName: 'Copperbelt Manufacturing', period: 'Year ended 31 December 2026', sections: [{ title: 'Prime cost', items: [{ name: 'Direct materials consumed', amount: 50000 }, { name: 'Direct labour', amount: 30000 }] }, { title: 'Factory overheads', items: [{ name: 'Factory rent', amount: 10000 }, { name: 'Factory depreciation', amount: 6000 }] }, { title: 'Work in progress adjustment', items: [{ name: 'Opening WIP', amount: 5000 }, { name: 'Closing WIP', amount: -7000 }] }] }),
  table('partnership_appropriation_account', 'Partnership appropriation account', 'advanced', 'Partnerships', 'case_study', 'Net profit, salaries, interest on capital, interest on drawings, and residual profit sharing.', { tableKind: 'partnership_appropriation_account', columns: ['Item', 'Partner A', 'Partner B', 'Total'], rows: [['Net profit', '', '', '60,000'], ['Partner salaries', '12,000', '8,000', '20,000'], ['Interest on capital', '3,000', '2,000', '5,000'], ['Residual profit share', '21,000', '14,000', '35,000']], required: ['Prepare appropriation account', 'Post current account entries'] }),
  table('partner_current_accounts', 'Partner current accounts', 'advanced', 'Partnerships', 'ledger', 'Current account movements for salaries, interest, drawings, and profit share.', { currency: 'ZMW', tableKind: 'partner_current_accounts', accountName: 'Partner Current Accounts', debitEntries: [{ details: 'Drawings - Partner A', amount: 6000 }, { details: 'Drawings - Partner B', amount: 4000 }], creditEntries: [{ details: 'Salary - Partner A', amount: 12000 }, { details: 'Salary - Partner B', amount: 8000 }, { details: 'Profit share', amount: 35000 }] }),
  table('company_statement_of_changes_in_equity', 'Statement of changes in equity', 'advanced', 'Company accounts', 'case_study', 'Share capital, retained earnings, profit, dividends, and closing equity.', { tableKind: 'statement_of_changes_in_equity', columns: ['Item', 'Share capital', 'Retained earnings', 'Total equity'], rows: [['Opening balance', '100,000', '25,000', '125,000'], ['Profit for the year', '', '40,000', '40,000'], ['Dividends', '', '(10,000)', '(10,000)'], ['Closing balance', '100,000', '55,000', '155,000']], required: ['Calculate closing retained earnings', 'Explain dividend treatment'] }),
  table('cash_flow_statement_working', 'Cash flow statement working table', 'advanced', 'Cash flows', 'cash_flow_statement', 'Operating, investing, and financing cash-flow classification with working notes.', { currency: 'ZMW', standardFramework: 'IFRS', tableKind: 'cash_flow_statement_working', statementType: 'cash_flow_statement', businessName: 'UnivAI Limited', period: 'Year ended 31 December 2026', sections: [{ title: 'Operating activities', items: [{ name: 'Profit before tax', amount: 60000 }, { name: 'Depreciation add-back', amount: 12000 }, { name: 'Increase in receivables', amount: -8000 }] }, { title: 'Investing activities', items: [{ name: 'Purchase of equipment', amount: -30000 }] }, { title: 'Financing activities', items: [{ name: 'Loan received', amount: 20000 }, { name: 'Dividends paid', amount: -10000 }] }] }),
  table('consolidation_working_schedule', 'Consolidation working schedule', 'advanced', 'Group accounts', 'consolidation', 'Goodwill, NCI, retained earnings, fair value adjustment, and intra-group elimination workings.', { currency: 'ZMW', standardFramework: 'IFRS', tableKind: 'consolidation_working_schedule', statementType: 'group_accounts', businessName: 'Parent Group', period: 'Year ended 31 December 2026', sections: [{ title: 'Goodwill working', items: [{ name: 'Consideration transferred', amount: 180000 }, { name: 'NCI at acquisition', amount: 40000 }, { name: 'Fair value of net assets acquired', amount: -190000 }] }, { title: 'Intra-group elimination', items: [{ name: 'Intra-group sales', amount: -20000 }, { name: 'Unrealised profit in inventory', amount: -4000 }] }] }),
  table('cost_sheet', 'Cost sheet', 'advanced', 'Cost accounting', 'case_study', 'Direct materials, direct labour, overheads, production cost, selling cost, and total cost.', { tableKind: 'cost_sheet', columns: ['Cost element', 'Amount'], rows: [['Direct materials', '50,000'], ['Direct labour', '30,000'], ['Factory overheads', '20,000'], ['Cost of production', '100,000'], ['Selling and distribution', '15,000'], ['Total cost', '115,000']], required: ['Calculate prime cost', 'Calculate cost of production', 'Calculate total cost and unit cost'] }),
  table('cash_budget', 'Cash budget', 'advanced', 'Budgeting', 'budgeting', 'Monthly receipts, payments, net cash flow, opening balance, and closing balance.', { tableKind: 'cash_budget', caseTitle: 'Three-month cash budget', columns: ['Item', 'January', 'February', 'March'], rows: [['Opening balance', '5,000', '7,000', '4,000'], ['Cash receipts', '20,000', '18,000', '25,000'], ['Cash payments', '(18,000)', '(21,000)', '(19,000)'], ['Closing balance', '7,000', '4,000', '10,000']], required: ['Prepare monthly cash budget', 'Identify cash deficit risk', 'Recommend financing action'] }),
  table('variance_analysis_table', 'Variance analysis table', 'advanced', 'Management accounting', 'variance_analysis', 'Standard, actual, variance, favourable/adverse classification, and performance interpretation.', { tableKind: 'variance_analysis_table', caseTitle: 'Material and labour variances', columns: ['Variance', 'Standard', 'Actual', 'Variance amount', 'F/A', 'Interpretation'], rows: [['Material price', 'K10/unit', 'K12/unit', 'K2 adverse per unit', 'A', 'Supplier price increased'], ['Labour rate', 'K20/hour', 'K18/hour', 'K2 favourable per hour', 'F', 'Lower wage rate']], required: ['Calculate variance', 'Classify favourable/adverse', 'Explain operational meaning'] }),
];

export const professionalAccountingTables: AccountingTableTemplate[] = [
  table('ifrs_recognition_measurement_disclosure_matrix', 'IFRS recognition-measurement-disclosure matrix', 'professional', 'Financial reporting', 'ifrs_treatment', 'Professional matrix for IFRS issue, recognition, measurement, presentation, disclosure, and judgement.', { standardFramework: 'IFRS', evidenceStandard: 'Professional judgement supported by recognition, measurement, presentation, disclosure, and conclusion.', tableKind: 'ifrs_rmd_matrix', caseTitle: 'IFRS treatment matrix', columns: ['Issue', 'Recognition', 'Measurement', 'Presentation', 'Disclosure', 'Judgement'], rows: [['Lease', 'Recognise right-of-use asset and lease liability if contract contains a lease', 'Present value of lease payments', 'Asset/liability presentation', 'Lease terms and maturity analysis', 'Assess control and identified asset']], required: ['Identify IFRS issue', 'Apply recognition and measurement', 'State presentation and disclosure', 'Defend judgement'] }),
  table('audit_risk_assertion_procedure_matrix', 'Audit risk-assertion-procedure matrix', 'professional', 'Audit', 'audit_risk', 'Risk, assertion, control weakness, audit procedure, and expected evidence.', { evidenceStandard: 'Professional skepticism with risk, assertion, procedure, and evidence linkage.', tableKind: 'audit_risk_matrix', columns: ['Risk', 'Assertion', 'Control weakness', 'Audit procedure', 'Expected evidence'], rows: [['Cash receipts may be incomplete', 'Completeness', 'One person records and banks cash', 'Trace receipts to bank statements and receipt sequence', 'Receipt sequence, bank deposit slips, reconciliations']], required: ['Identify audit risks', 'Link assertions', 'Recommend audit procedures', 'State expected evidence'] }),
  table('tax_computation_schedule', 'Tax computation schedule', 'professional', 'Taxation', 'tax_computation', 'Accounting profit, add-backs, deductions, capital allowances, taxable profit, credits, and tax payable.', { jurisdiction: 'Zambia', taxYear: '2026', evidenceStandard: 'Jurisdiction-specific computation with clear assumptions.', tableKind: 'tax_computation_schedule', columns: ['Item', 'Amount'], rows: [['Accounting profit', '180,000'], ['Add: disallowable expenses', '20,000'], ['Less: capital allowances', '(35,000)'], ['Taxable profit', '165,000'], ['Less: withholding tax credits', '(5,000)']], required: ['Compute taxable profit', 'Compute tax payable', 'Explain treatment of adjustments'] }),
];

export const accountingTableCatalog = [...beginnerAccountingTables, ...intermediateAccountingTables, ...advancedAccountingTables, ...professionalAccountingTables];
export const accountingTableTemplateLabels = accountingTableCatalog.map((template) => template.label);
export function applyAccountingTableTemplate(label: string) { return accountingTableCatalog.find((template) => template.label === label); }

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
