import type { AccountingTableLevel, AccountingTableTemplate } from './table-catalog';

export const taxPayrollAccountingTables: AccountingTableTemplate[] = [
  table('company_income_tax_full_computation', 'Full company income tax computation', 'professional', 'Taxation', 'tax_computation', 'Full corporate tax computation from accounting profit to tax payable.', { jurisdiction: 'Zambia', taxYear: '2026', evidenceStandard: 'Jurisdiction-specific tax computation with assumptions.', tableKind: 'company_income_tax_computation', columns: ['Item', 'Amount'], rows: [['Accounting profit before tax', '500,000'], ['Add: disallowable expenses', '75,000'], ['Less: exempt income', '(20,000)'], ['Less: capital allowances', '(100,000)'], ['Taxable income', '455,000'], ['Company income tax', '136,500'], ['Less: tax credits', '(10,000)'], ['Tax payable', '126,500']], required: ['Calculate taxable income', 'Calculate tax payable', 'Explain adjustments'] }),
  table('personal_income_tax_computation', 'Personal income tax computation', 'professional', 'Taxation', 'tax_computation', 'Personal income tax computation with bands, reliefs, and net tax payable.', { jurisdiction: 'Zambia', taxYear: '2026', evidenceStandard: 'Personal tax computation using applicable bands and assumptions.', tableKind: 'personal_income_tax_computation', columns: ['Band/item', 'Taxable amount', 'Rate', 'Tax'], rows: [['First band', '57,600', '0%', '0'], ['Second band', '24,000', '20%', '4,800'], ['Third band', '36,000', '30%', '10,800'], ['Balance', '50,000', '37.5%', '18,750']], required: ['Apply tax bands', 'Calculate total PAYE/tax payable'] }),
  table('paye_monthly_return', 'PAYE monthly return table', 'professional', 'Payroll tax', 'tax_computation', 'PAYE return listing employees, taxable pay, tax deducted, and total remittance.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'paye_monthly_return', columns: ['Employee', 'TPIN/ID', 'Gross taxable pay', 'PAYE deducted', 'Net pay'], rows: [['A. Banda', '1001', '8,000', '900', '7,100'], ['C. Muloongo', '1002', '12,000', '2,100', '9,900']], required: ['Calculate PAYE per employee', 'Total PAYE remittance'] }),
  table('napsa_contribution_schedule', 'NAPSA employer/employee contribution schedule', 'professional', 'Payroll tax', 'tax_computation', 'NAPSA contribution schedule showing employee and employer obligations.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'napsa_contribution_schedule', columns: ['Employee', 'Pensionable earnings', 'Employee contribution', 'Employer contribution', 'Total NAPSA'], rows: [['A. Banda', '8,000', '400', '400', '800'], ['C. Muloongo', '12,000', '600', '600', '1,200']], required: ['Calculate employee contribution', 'Calculate employer contribution'] }),
  table('nhima_contribution_schedule', 'NHIMA contribution schedule', 'professional', 'Payroll tax', 'tax_computation', 'NHIMA employee/employer health insurance contribution schedule.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'nhima_contribution_schedule', columns: ['Employee', 'Basic salary', 'Employee NHIMA', 'Employer NHIMA', 'Total'], rows: [['A. Banda', '8,000', '80', '80', '160'], ['C. Muloongo', '12,000', '120', '120', '240']], required: ['Calculate NHIMA contributions', 'Explain payroll deduction'] }),
  table('turnover_tax_computation', 'Turnover tax computation', 'professional', 'Taxation', 'tax_computation', 'Turnover tax computation for qualifying small businesses.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'turnover_tax_computation', columns: ['Item', 'Amount'], rows: [['Monthly turnover', '80,000'], ['Exempt turnover', '(5,000)'], ['Taxable turnover', '75,000'], ['Tax rate', '4%'], ['Turnover tax payable', '3,000']], required: ['Calculate taxable turnover', 'Calculate turnover tax payable'] }),
  table('rental_income_tax_computation', 'Rental income tax computation', 'professional', 'Taxation', 'tax_computation', 'Rental income tax schedule for gross rent, allowable deductions, and tax payable.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'rental_income_tax_computation', columns: ['Item', 'Amount'], rows: [['Gross rental income', '120,000'], ['Allowable expenses', '(20,000)'], ['Taxable rental income', '100,000'], ['Tax payable', '10,000']], required: ['Calculate taxable rental income', 'Calculate rental tax'] }),
  table('property_transfer_tax_table', 'Property transfer tax table', 'professional', 'Taxation', 'tax_computation', 'Property transfer tax computation on sale or transfer of qualifying property.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'property_transfer_tax', columns: ['Property', 'Transfer value', 'Rate', 'Tax'], rows: [['Commercial property', '1,000,000', '5%', '50,000'], ['Shares transfer', '300,000', '5%', '15,000']], required: ['Identify taxable transfer', 'Calculate property transfer tax'] }),
  table('customs_import_duty_computation', 'Customs/import duty computation', 'professional', 'Taxation', 'tax_computation', 'Computes landed cost using customs value, duty, excise, VAT, and charges.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'customs_import_duty', columns: ['Item', 'Amount'], rows: [['Customs value', '200,000'], ['Import duty 15%', '30,000'], ['Excise duty', '10,000'], ['VAT base', '240,000'], ['Import VAT 16%', '38,400'], ['Landed tax cost', '78,400']], required: ['Calculate import duty', 'Calculate VAT base', 'Calculate landed tax cost'] }),
  table('vat_apportionment_table', 'VAT apportionment table', 'professional', 'VAT', 'tax_computation', 'Apportions input VAT between taxable and exempt supplies.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'vat_apportionment', columns: ['Item', 'Amount'], rows: [['Taxable supplies', '800,000'], ['Exempt supplies', '200,000'], ['Recovery ratio', '80%'], ['Common input VAT', '50,000'], ['Recoverable input VAT', '40,000']], required: ['Calculate recovery ratio', 'Calculate recoverable input VAT'] }),
  table('vat_partial_exemption_table', 'VAT partial exemption table', 'professional', 'VAT', 'tax_computation', 'Partial exemption calculation and de minimis assessment.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'vat_partial_exemption', columns: ['Input VAT type', 'Amount', 'Recoverable?', 'Reason'], rows: [['Direct taxable input VAT', '20,000', 'Yes', 'Relates to taxable supplies'], ['Direct exempt input VAT', '8,000', 'No', 'Relates to exempt supplies'], ['Residual input VAT', '12,000', 'Partly', 'Apportion by recovery ratio']], required: ['Classify input VAT', 'Apply partial exemption rule'] }),
  table('vat_bad_debt_relief', 'VAT bad debt relief table', 'professional', 'VAT', 'tax_computation', 'Determines VAT relief on unpaid sales debts written off.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'vat_bad_debt_relief', columns: ['Customer', 'Gross debt', 'VAT element', 'Age', 'Relief claimable?'], rows: [['Banda Stores', '11,600', '1,600', '12 months', 'Yes'], ['Copper Mart', '5,800', '800', '3 months', 'No']], required: ['Calculate VAT element', 'Assess relief eligibility'] }),
  table('vat_reverse_charge_table', 'VAT reverse charge table', 'professional', 'VAT', 'tax_computation', 'Reverse charge VAT on imported services or cross-border transactions.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'vat_reverse_charge', columns: ['Service', 'Supplier location', 'Taxable value', 'Reverse charge VAT', 'Input claim'], rows: [['Cloud software', 'Foreign', '20,000', '3,200', '3,200 if taxable use']], required: ['Calculate reverse charge VAT', 'Explain output/input treatment'] }),
  table('tax_penalties_interest_schedule', 'Tax penalties and interest schedule', 'professional', 'Taxation', 'tax_computation', 'Computes penalties and interest for late filing/payment.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'tax_penalties_interest', columns: ['Tax type', 'Principal tax', 'Penalty', 'Interest', 'Total due'], rows: [['VAT', '30,000', '3,000', '1,200', '34,200'], ['PAYE', '15,000', '1,500', '600', '17,100']], required: ['Calculate penalties', 'Calculate total liability'] }),
  table('tax_payable_reconciliation', 'Tax payable reconciliation', 'professional', 'Taxation', 'tax_computation', 'Reconciles tax expense, tax paid, credits, and closing payable.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'tax_payable_reconciliation', columns: ['Item', 'Amount'], rows: [['Opening tax payable', '20,000'], ['Current tax charge', '100,000'], ['Tax paid', '(85,000)'], ['Withholding tax credits', '(10,000)'], ['Closing tax payable', '25,000']], required: ['Reconcile tax payable', 'Explain tax credits'] }),
  table('provisional_tax_instalment_table', 'Tax instalment/provisional tax table', 'professional', 'Taxation', 'tax_computation', 'Quarterly provisional tax estimate, instalments, and final balancing payment.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'provisional_tax_instalments', columns: ['Instalment', 'Due period', 'Estimated tax', 'Payment', 'Balance'], rows: [['Q1', 'March', '120,000', '30,000', '90,000'], ['Q2', 'June', '120,000', '30,000', '60,000'], ['Q3', 'September', '120,000', '30,000', '30,000'], ['Q4', 'December', '120,000', '30,000', '0']], required: ['Calculate instalments', 'Determine final balancing tax'] }),
  table('transfer_pricing_adjustment', 'Transfer pricing adjustment table', 'professional', 'Taxation', 'tax_computation', 'Adjusts related-party prices to arm’s-length price.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'transfer_pricing_adjustment', columns: ['Transaction', 'Related-party price', 'Arm’s-length price', 'Adjustment'], rows: [['Management service fee', '100,000', '70,000', '30,000 add-back'], ['Inventory purchase', '200,000', '180,000', '20,000 add-back']], required: ['Identify non-arm’s-length pricing', 'Calculate tax adjustment'] }),
  table('thin_capitalisation_interest_limit', 'Thin capitalisation/interest limitation table', 'professional', 'Taxation', 'tax_computation', 'Determines deductible and disallowed interest under financing restrictions.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'thin_capitalisation_interest_limit', columns: ['Item', 'Amount'], rows: [['Interest expense', '120,000'], ['Allowable limit', '80,000'], ['Disallowed interest', '40,000'], ['Deductible interest', '80,000']], required: ['Calculate disallowed interest', 'Adjust taxable income'] }),
  table('capital_gains_property_disposal_tax', 'Capital gains/property disposal tax table', 'professional', 'Taxation', 'tax_computation', 'Computes taxable gain or transfer tax on disposal.', { jurisdiction: 'Zambia', taxYear: '2026', tableKind: 'capital_gains_property_disposal', columns: ['Item', 'Amount'], rows: [['Sale proceeds', '500,000'], ['Cost/base value', '(300,000)'], ['Incidental costs', '(20,000)'], ['Taxable gain/value', '180,000']], required: ['Calculate gain/value', 'Apply relevant tax treatment'] }),
];

function table(id: string, label: string, level: AccountingTableLevel, area: string, accountingType: string, description: string, data: Record<string, unknown>, expectedAnswer?: Record<string, unknown>): AccountingTableTemplate {
  return { id, label, level, area, accountingType, description, data, expectedAnswer };
}
